//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACPA_APG
    {
        public string APG_APNU { get; set; }
        public string APG_CDEC { get; set; }
        public string APG_AGRA { get; set; }
        public string APG_PGRA { get; set; }
        public System.DateTime APG_FNOV { get; set; }
        public string APG_USBD { get; set; }
        public string APG_USAP { get; set; }
        public System.DateTime APG_FREG { get; set; }
    
        public virtual ACUE_PAGO ACUE_PAGO { get; set; }
        public virtual CALENDARIO CALENDARIO { get; set; }
    }
}
