//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANCOS
    {
        public BANCOS()
        {
            this.CTA_BANCO = new HashSet<CTA_BANCO>();
        }
    
        public string BAN_COD { get; set; }
        public string BAN_NOM { get; set; }
        public string BAN_USAP { get; set; }
        public string BAN_USBD { get; set; }
        public string BAN_EST { get; set; }
        public Nullable<System.DateTime> BAN_FREG { get; set; }
        public Nullable<System.DateTime> BAN_FNOV { get; set; }
    
        public virtual ICollection<CTA_BANCO> CTA_BANCO { get; set; }
    }
}
