//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASE_DEC
    {
        public CLASE_DEC()
        {
            this.ACUE_PAGO = new HashSet<ACUE_PAGO>();
            this.CALENDARIO = new HashSet<CALENDARIO>();
            this.CLD_IMP = new HashSet<CLD_IMP>();
            this.CODE_CDEC = new HashSet<CODE_CDEC>();
            this.CONC_CDEC = new HashSet<CONC_CDEC>();
            this.DIST_CART = new HashSet<DIST_CART>();
            this.EXPEDIENTES = new HashSet<EXPEDIENTES>();
            this.FORMULARIOS_DEC = new HashSet<FORMULARIOS_DEC>();
            this.REQUI_DECLARACION = new HashSet<REQUI_DECLARACION>();
            this.TER_DEC = new HashSet<TER_DEC>();
            this.TIPO_DEC = new HashSet<TIPO_DEC>();
        }
    
        public string CLD_COD { get; set; }
        public string CLD_NOM { get; set; }
        public string CLD_USBD { get; set; }
        public string CLD_USAP { get; set; }
        public System.DateTime CLD_FREG { get; set; }
        public System.DateTime CLD_FNOV { get; set; }
        public System.DateTime CLD_FIN { get; set; }
        public System.DateTime CLD_FFI { get; set; }
        public string CLD_CONS { get; set; }
        public string CLD_EST { get; set; }
    
        public virtual ICollection<ACUE_PAGO> ACUE_PAGO { get; set; }
        public virtual ICollection<CALENDARIO> CALENDARIO { get; set; }
        public virtual ICollection<CLD_IMP> CLD_IMP { get; set; }
        public virtual ICollection<CODE_CDEC> CODE_CDEC { get; set; }
        public virtual ICollection<CONC_CDEC> CONC_CDEC { get; set; }
        public virtual ICollection<DIST_CART> DIST_CART { get; set; }
        public virtual ICollection<EXPEDIENTES> EXPEDIENTES { get; set; }
        public virtual ICollection<FORMULARIOS_DEC> FORMULARIOS_DEC { get; set; }
        public virtual ICollection<REQUI_DECLARACION> REQUI_DECLARACION { get; set; }
        public virtual ICollection<TER_DEC> TER_DEC { get; set; }
        public virtual ICollection<TIPO_DEC> TIPO_DEC { get; set; }
    }
}
