//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLD_IMP
    {
        public string CLD_COD { get; set; }
        public string CLD_CIMP { get; set; }
        public string CLD_ABIM { get; set; }
        public string CLD_ABVA { get; set; }
        public Nullable<System.DateTime> CLD_FNOV { get; set; }
        public Nullable<System.DateTime> CLD_FREG { get; set; }
        public string CLD_USAP { get; set; }
        public string CLD_USBD { get; set; }
    
        public virtual CLASE_DEC CLASE_DEC { get; set; }
        public virtual IMPUESTOS IMPUESTOS { get; set; }
    }
}
