//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTAMENTOS
    {
        public string COD_DEPTO { get; set; }
        public string NOM_DEPTO { get; set; }
        public string ABREV_DISFON { get; set; }
        public string USAP { get; set; }
        public string USBD { get; set; }
        public Nullable<System.DateTime> FREG { get; set; }
        public Nullable<System.DateTime> FNOV { get; set; }
    }
}
