//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPAGO_ROAP
    {
        public string DPAP_APNU { get; set; }
        public int DPAP_CUNU { get; set; }
        public int DPAP_PAGO { get; set; }
        public System.DateTime DPAP_FEPA { get; set; }
        public System.DateTime DPAP_FREG { get; set; }
        public string DPAP_USBD { get; set; }
        public string DPAP_USAP { get; set; }
        public Nullable<System.DateTime> DPAP_FNOV { get; set; }
        public string DPAP_RNUM { get; set; }
    }
}
