//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTIDAD
    {
        public string ENT_NIT { get; set; }
        public string ENT_NOM { get; set; }
        public string ENT_DIR { get; set; }
        public string ENT_TEL { get; set; }
        public string ENT_EMAIL { get; set; }
        public string ENT_DPTO { get; set; }
        public string ENT_MPIO { get; set; }
        public string ENT_CEDRES { get; set; }
        public string ENT_NOMRES { get; set; }
        public string ENT_LOGO { get; set; }
        public string ENT_USAP { get; set; }
        public string ENT_USBD { get; set; }
        public Nullable<System.DateTime> ENT_FREG { get; set; }
        public Nullable<System.DateTime> ENT_FNOV { get; set; }
    }
}
