//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPE_TRAM
    {
        public string EXTR_NUME { get; set; }
        public string EXTR_DOAD { get; set; }
        public System.DateTime EXTR_FELA { get; set; }
        public string EXTR_TANT { get; set; }
        public string EXTR_TACT { get; set; }
        public string EXTR_TRNU { get; set; }
        public string EXTR_RENI { get; set; }
        public string EXTR_TRPT { get; set; }
        public string EXTR_RPTA { get; set; }
        public string EXTR_OBSE { get; set; }
        public string EXTR_ADJU { get; set; }
        public string EXTR_ANEX { get; set; }
        public string EXTR_USAP { get; set; }
        public string EXTR_USBD { get; set; }
        public System.DateTime EXTR_FREG { get; set; }
        public string EXTR_DONU { get; set; }
        public byte[] EXTR_PLAN { get; set; }
        public Nullable<System.DateTime> EXPE_FREB { get; set; }
        public Nullable<System.DateTime> EXPE_FEXP { get; set; }
        public string EXPE_NOTIF { get; set; }
        public byte[] EXTR_DOC { get; set; }
        public Nullable<decimal> EXTR_ID { get; set; }
        public string EXTR_DATO1 { get; set; }
        public byte[] EXTR_PDF { get; set; }
    
        public virtual EXPEDIENTES EXPEDIENTES { get; set; }
    }
}
