//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMULASL
    {
        public string FORM_CODI { get; set; }
        public System.DateTime FORM_FEIN { get; set; }
        public System.DateTime FORM_FEFI { get; set; }
        public string FORM_FORM { get; set; }
        public string FORM_NORM { get; set; }
        public string FORM_CONC { get; set; }
        public string FORM_USAP { get; set; }
        public string FORM_USBD { get; set; }
        public Nullable<System.DateTime> FORM_FREG { get; set; }
        public Nullable<System.DateTime> FORM_FNOV { get; set; }
    }
}
