//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPUESTOS
    {
        public IMPUESTOS()
        {
            this.CLD_IMP = new HashSet<CLD_IMP>();
            this.FORMULASLT = new HashSet<FORMULASLT>();
        }
    
        public string IMP_COD { get; set; }
        public string IMP_NOM { get; set; }
        public string IMP_OBS { get; set; }
        public string IMP_NOR { get; set; }
        public string IMP_CLA { get; set; }
        public string IMP_UNI { get; set; }
        public string IMP_USAP { get; set; }
        public string IMP_USBD { get; set; }
        public Nullable<System.DateTime> IMP_FREG { get; set; }
        public Nullable<System.DateTime> IMP_FNOV { get; set; }
    
        public virtual ICollection<CLD_IMP> CLD_IMP { get; set; }
        public virtual ICollection<FORMULASLT> FORMULASLT { get; set; }
        public virtual UNIDAD UNIDAD { get; set; }
    }
}
