//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public MENU()
        {
            this.MENU1 = new HashSet<MENU>();
            this.MENU_PERFIL = new HashSet<MENU_PERFIL>();
        }
    
        public string MENUID { get; set; }
        public string TITULO { get; set; }
        public string DESCRIPCION { get; set; }
        public string PADREID { get; set; }
        public int POSICION { get; set; }
        public string ICONO { get; set; }
        public short HABILITADO { get; set; }
        public string URL { get; set; }
        public string MODULO { get; set; }
        public string ROLES { get; set; }
        public string TARGET { get; set; }
        public string PPAL { get; set; }
        public string USAP { get; set; }
        public string USBD { get; set; }
        public Nullable<System.DateTime> FREG { get; set; }
        public Nullable<System.DateTime> FNOV { get; set; }
    
        public virtual ICollection<MENU> MENU1 { get; set; }
        public virtual MENU MENU2 { get; set; }
        public virtual ICollection<MENU_PERFIL> MENU_PERFIL { get; set; }
    }
}
