//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARA_LIQU
    {
        public PARA_LIQU()
        {
            this.PAR_LIQ_DET = new HashSet<PAR_LIQ_DET>();
        }
    
        public string PALI_CODI { get; set; }
        public string PALI_NOMB { get; set; }
        public string PALI_TIDA { get; set; }
        public string PALI_VARI { get; set; }
        public string PALI_ESTA { get; set; }
        public string PALI_DESC { get; set; }
        public string PALI_USAP { get; set; }
        public string PALI_USBD { get; set; }
        public Nullable<System.DateTime> PALI_FREG { get; set; }
        public Nullable<System.DateTime> PALI_FNOV { get; set; }
    
        public virtual ICollection<PAR_LIQ_DET> PAR_LIQ_DET { get; set; }
        public virtual TIPO_DATO TIPO_DATO { get; set; }
    }
}
