//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARIFAS_IMP
    {
        public System.DateTime TARI_FEIN { get; set; }
        public System.DateTime TARI_FEFI { get; set; }
        public string TARI_FORM { get; set; }
        public string TARI_NORM { get; set; }
        public string TARI_IMP { get; set; }
        public string TARI_CODI { get; set; }
        public string TARI_USAP { get; set; }
        public string TARI_USBD { get; set; }
        public Nullable<System.DateTime> TARI_FREG { get; set; }
        public Nullable<System.DateTime> TARI_FNOV { get; set; }
    }
}
