//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_CUENTA
    {
        public TIPO_CUENTA()
        {
            this.CTA_BANCO = new HashSet<CTA_BANCO>();
        }
    
        public string TCTA_CODI { get; set; }
        public string TCTA_NOMB { get; set; }
        public string TCTA_USAP { get; set; }
        public string TCTA_USBD { get; set; }
        public Nullable<System.DateTime> TCTA_FREG { get; set; }
        public Nullable<System.DateTime> TCTA_FNOV { get; set; }
    
        public virtual ICollection<CTA_BANCO> CTA_BANCO { get; set; }
    }
}
