//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PAGO
    {
        public string TPAG_COD { get; set; }
        public string TPAG_NOM { get; set; }
        public string TPAG_USAP { get; set; }
        public string TPAG_USBD { get; set; }
        public Nullable<System.DateTime> TPAG_FREG { get; set; }
        public Nullable<System.DateTime> TPAG_FNOV { get; set; }
    }
}
