//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_DOC_CONS
    {
        public string TIDO_CODI { get; set; }
        public string TIDO_CDEC { get; set; }
        public string TIDO_CONS { get; set; }
        public string TIDO_USAP { get; set; }
        public string TIDO_USBD { get; set; }
        public Nullable<System.DateTime> TIDO_FREG { get; set; }
        public Nullable<System.DateTime> TIDO_FNOV { get; set; }
    
        public virtual TIPO_DOC TIPO_DOC { get; set; }
    }
}
