//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_DATO
    {
        public TIPO_DATO()
        {
            this.FMTO_IMP = new HashSet<FMTO_IMP>();
            this.PARA_LIQU = new HashSet<PARA_LIQU>();
        }
    
        public string TIDA_CODI { get; set; }
        public string TIDA_ORACLE { get; set; }
        public string TIDA_NET { get; set; }
        public string TIDA_USAP { get; set; }
        public string TIDA_USBD { get; set; }
        public System.DateTime TIDA_FREG { get; set; }
        public System.DateTime TIDA_FNOV { get; set; }
    
        public virtual ICollection<FMTO_IMP> FMTO_IMP { get; set; }
        public virtual ICollection<PARA_LIQU> PARA_LIQU { get; set; }
    }
}
