//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_MOV
    {
        public TIPO_MOV()
        {
            this.MOVIMIENTO = new HashSet<MOVIMIENTO>();
        }
    
        public string TMOV_COD { get; set; }
        public string TMOV_NOM { get; set; }
        public string TMOV_USAP { get; set; }
        public string TMOV_USBD { get; set; }
        public Nullable<System.DateTime> TMOV_FREG { get; set; }
        public Nullable<System.DateTime> TMOV_FNOV { get; set; }
    
        public virtual ICollection<MOVIMIENTO> MOVIMIENTO { get; set; }
    }
}
