//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_SANCIONES
    {
        public string TSAN_COD { get; set; }
        public string TSAN_NOM { get; set; }
        public string TSAN_FORM { get; set; }
        public string TSAN_PAR { get; set; }
        public string TSAN_DEC { get; set; }
        public string TSAN_DETI { get; set; }
        public string TSAN_USAP { get; set; }
        public string TSAN_USBD { get; set; }
        public Nullable<System.DateTime> TSAN_FREG { get; set; }
        public Nullable<System.DateTime> TSAN_FNOV { get; set; }
    }
}
