//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOUSUA
    {
        public string TUS_COD { get; set; }
        public string TUS_NOM { get; set; }
        public string TUS_USAP { get; set; }
        public string TUS_USBD { get; set; }
        public Nullable<System.DateTime> TUS_FREG { get; set; }
        public Nullable<System.DateTime> TUS_FNOV { get; set; }
    }
}
