//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PROCESO
    {
        public TIPO_PROCESO()
        {
            this.EXPEDIENTES = new HashSet<EXPEDIENTES>();
            this.PROCESOS = new HashSet<PROCESOS>();
        }
    
        public string TPRO_CODI { get; set; }
        public string TPRO_NOMB { get; set; }
        public string TPRO_USAP { get; set; }
        public string TPRO_USBD { get; set; }
        public Nullable<System.DateTime> TPRO_FREG { get; set; }
        public Nullable<System.DateTime> TPRO_FNOV { get; set; }
    
        public virtual ICollection<EXPEDIENTES> EXPEDIENTES { get; set; }
        public virtual ICollection<PROCESOS> PROCESOS { get; set; }
    }
}
