//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAM_TER
    {
        public string TRTE_NIT { get; set; }
        public string TRTE_TRAM { get; set; }
        public string TRTE_USAP { get; set; }
        public string TRTE_USBD { get; set; }
        public Nullable<System.DateTime> TRTE_FREG { get; set; }
        public Nullable<System.DateTime> TRTE_FNOV { get; set; }
    }
}
