//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAMRELA
    {
        public string TRRE_DESD { get; set; }
        public string TRRE_PARA { get; set; }
        public short TRRE_DILI { get; set; }
        public string TRRE_USAP { get; set; }
        public string TRRE_USBD { get; set; }
        public Nullable<System.DateTime> TRRE_FREG { get; set; }
        public Nullable<System.DateTime> TRRE_FNOV { get; set; }
    }
}
