//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VH_BG_AUTO_2009
    {
        public int GRUPO { get; set; }
        public string MARCA { get; set; }
        public string LINEA { get; set; }
        public string LINEA_H { get; set; }
        public Nullable<int> CILINDRADA { get; set; }
        public Nullable<decimal> V1984 { get; set; }
        public Nullable<decimal> V1985 { get; set; }
        public Nullable<decimal> V1986 { get; set; }
        public Nullable<decimal> V1987 { get; set; }
        public Nullable<decimal> V1988 { get; set; }
        public Nullable<decimal> V1989 { get; set; }
        public Nullable<decimal> V1990 { get; set; }
        public Nullable<decimal> V1991 { get; set; }
        public Nullable<decimal> V1992 { get; set; }
        public Nullable<decimal> V1993 { get; set; }
        public Nullable<decimal> V1994 { get; set; }
        public Nullable<decimal> V1995 { get; set; }
        public Nullable<decimal> V1996 { get; set; }
        public Nullable<decimal> V1997 { get; set; }
        public Nullable<decimal> V1998 { get; set; }
        public Nullable<decimal> V1999 { get; set; }
        public Nullable<decimal> V2000 { get; set; }
        public Nullable<decimal> V2001 { get; set; }
        public Nullable<decimal> V2002 { get; set; }
        public Nullable<decimal> V2003 { get; set; }
        public Nullable<decimal> V2004 { get; set; }
        public Nullable<decimal> V2005 { get; set; }
        public Nullable<decimal> V2006 { get; set; }
        public Nullable<decimal> V2007 { get; set; }
        public Nullable<decimal> V2008 { get; set; }
    }
}
