//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VH_LIQ_GRUPAL
    {
        public int NRO_LIQG { get; set; }
        public Nullable<System.DateTime> FECHA_INI { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public string USBD { get; set; }
        public string USAP { get; set; }
        public string ESTADO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    }
}
