//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANULACIONES
    {
        public string ANUL_TDAN { get; set; }
        public string ANUL_NDAN { get; set; }
        public string ANUL_TDOC { get; set; }
        public string ANUL_NDOC { get; set; }
        public string ANUL_OBSE { get; set; }
        public Nullable<System.DateTime> ANUL_FREG { get; set; }
        public string ANUL_USAP { get; set; }
        public string ANUL_USBD { get; set; }
        public string ANUL_EST { get; set; }
    }
}
