//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTERAD
    {
        public string CAR_ID { get; set; }
        public string CAR_NIT { get; set; }
        public string CAR_ANO { get; set; }
        public string CAR_PER { get; set; }
        public string CAR_COCA { get; set; }
        public string CAR_TCON { get; set; }
        public long CAR_VADE { get; set; }
        public long CAR_VDB { get; set; }
        public long CAR_VCR { get; set; }
        public long CAR_VPA { get; set; }
        public string CAR_CDEC { get; set; }
        public string CAR_CCON { get; set; }
        public string CAR_CIMP { get; set; }
        public string CAR_TPAG { get; set; }
        public string CAR_VIG { get; set; }
        public System.DateTime CAR_FNOV { get; set; }
        public string CAR_EST { get; set; }
        public Nullable<System.DateTime> CAR_FREG { get; set; }
        public string CAR_USAP { get; set; }
        public string CAR_USBD { get; set; }
        public string CAR_DCOD { get; set; }
        public Nullable<System.DateTime> CAR_FVEN { get; set; }
        public string CAR_TDOC { get; set; }
        public string CAR_SUIM { get; set; }
        public string CAR_ACPA { get; set; }
    
        public virtual CALENDARIO CALENDARIO { get; set; }
        public virtual CONC_CART CONC_CART { get; set; }
        public virtual TIPO_CONCEPTOS TIPO_CONCEPTOS { get; set; }
        public virtual TIPO_DOC TIPO_DOC { get; set; }
    }
}
