//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASE_IMPTO
    {
        public string CLIM_CODI { get; set; }
        public string CLIM_NOMB { get; set; }
        public Nullable<System.DateTime> CLIM_FEIN { get; set; }
        public Nullable<System.DateTime> CLIM_FEFI { get; set; }
        public string CLIM_USBD { get; set; }
        public Nullable<System.DateTime> CLIM_FNOV { get; set; }
        public Nullable<System.DateTime> CLIM_FREG { get; set; }
        public string CLIM_USAP { get; set; }
    }
}
