//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONCEPTOS_IMP
    {
        public string COIM_CIMP { get; set; }
        public string COIM_COD { get; set; }
        public string COIM_NOM { get; set; }
        public string COIM_TARIFA { get; set; }
        public Nullable<System.DateTime> COIM_FNOV { get; set; }
        public string COIM_EST { get; set; }
        public string COIM_PRI { get; set; }
        public string COIM_TCON { get; set; }
        public string COIM_TMOV { get; set; }
        public Nullable<decimal> COIM_IDX { get; set; }
        public string COIM_USBD { get; set; }
        public string COIM_USAP { get; set; }
        public Nullable<System.DateTime> COIM_FREG { get; set; }
    }
}
