//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSECUTIVOS
    {
        public string CONS_VIG { get; set; }
        public int CONS_ID { get; set; }
        public string CONS_NOM { get; set; }
        public int CONS_PRX { get; set; }
        public int CONS_INI { get; set; }
        public string CONS_USAP { get; set; }
        public string CONS_USBD { get; set; }
        public Nullable<System.DateTime> CONS_FREG { get; set; }
        public Nullable<System.DateTime> CONS_FNOV { get; set; }
    
        public virtual VIGENCIA VIGENCIA { get; set; }
    }
}
