//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONT_PERI
    {
        public string COPE_AÑO { get; set; }
        public string COPE_MES { get; set; }
        public string COPE_ESTA { get; set; }
        public System.DateTime COPE_FNOV { get; set; }
        public string COPE_USBD { get; set; }
        public string COPE_USAP { get; set; }
        public Nullable<System.DateTime> COPE_FREG { get; set; }
    }
}
