//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORREOSE
    {
        public string CORR_CODI { get; set; }
        public string CORR_NOMB { get; set; }
        public string CORR_DATO { get; set; }
        public string CORR_BODY { get; set; }
        public string CORR_USAP { get; set; }
        public string CORR_USBD { get; set; }
        public Nullable<System.DateTime> CORR_FREG { get; set; }
        public Nullable<System.DateTime> CORR_FNOV { get; set; }
        public string CORR_CAMP { get; set; }
        public string CORR_VISTA { get; set; }
    }
}
