//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTA_BANCO
    {
        public CTA_BANCO()
        {
            this.PAGOS = new HashSet<PAGOS>();
            this.PAGOS_SOP = new HashSet<PAGOS_SOP>();
        }
    
        public string CTA_BACO { get; set; }
        public string CTA_NRO { get; set; }
        public string CTA_TIP { get; set; }
        public string CTA_CODBAR { get; set; }
        public string CTA_EST { get; set; }
        public string CTA_USAP { get; set; }
        public string CTA_USBD { get; set; }
        public string CTA_DESC { get; set; }
        public string CTA_SUC { get; set; }
        public Nullable<System.DateTime> CTA_FREG { get; set; }
        public Nullable<System.DateTime> CTA_FNOV { get; set; }
    
        public virtual BANCOS BANCOS { get; set; }
        public virtual TIPO_CUENTA TIPO_CUENTA { get; set; }
        public virtual ICollection<PAGOS> PAGOS { get; set; }
        public virtual ICollection<PAGOS_SOP> PAGOS_SOP { get; set; }
    }
}
