//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUOT_ACPA
    {
        public string CUAP_APNU { get; set; }
        public int CUAP_CUNU { get; set; }
        public int CUAP_VALO { get; set; }
        public int CUAP_PAGO { get; set; }
        public System.DateTime CUAP_FEPA { get; set; }
        public System.DateTime CUAP_FREG { get; set; }
        public string CUAP_USBD { get; set; }
        public string CUAP_USAP { get; set; }
        public Nullable<System.DateTime> CUAP_FNOV { get; set; }
    
        public virtual ACUE_PAGO ACUE_PAGO { get; set; }
    }
}
