//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIST_CART
    {
        public string DICA_CDEC { get; set; }
        public string DICA_CODD { get; set; }
        public string DICA_CODC { get; set; }
        public string DICA_FDCO { get; set; }
        public Nullable<short> DICA_ORDE { get; set; }
        public string DICA_USAP { get; set; }
        public string DICA_USBD { get; set; }
        public Nullable<System.DateTime> DICA_FREG { get; set; }
        public Nullable<System.DateTime> DICA_FNOV { get; set; }
    
        public virtual CLASE_DEC CLASE_DEC { get; set; }
        public virtual CONC_CART CONC_CART { get; set; }
        public virtual FORMULARIOS_DEC FORMULARIOS_DEC { get; set; }
    }
}
