//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADOS
    {
        public ESTADOS()
        {
            this.VIGENCIA = new HashSet<VIGENCIA>();
        }
    
        public string EST_COD { get; set; }
        public string EST_DES { get; set; }
        public string EST_USAP { get; set; }
        public string EST_USBD { get; set; }
        public Nullable<System.DateTime> EST_FREG { get; set; }
        public Nullable<System.DateTime> EST_FNOV { get; set; }
    
        public virtual ICollection<VIGENCIA> VIGENCIA { get; set; }
    }
}
