//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPE_ANULA
    {
        public string EXPE_NUME { get; set; }
        public string EXPE_ID { get; set; }
        public Nullable<System.DateTime> EXPE_FANU { get; set; }
        public string EXPE_OBSE { get; set; }
        public string TABLA { get; set; }
        public string EXPE_USAP { get; set; }
        public string EXPE_USBD { get; set; }
        public System.DateTime EXPE_FREG { get; set; }
    }
}
