//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAUDITORIA
    {
        public decimal HAUDCODI { get; set; }
        public string HAUDTABL { get; set; }
        public string HAUDIDEN { get; set; }
        public string HAUDTIPO { get; set; }
        public string HAUDDESC { get; set; }
        public string HAUDUSER { get; set; }
        public System.DateTime HAUDFESI { get; set; }
        public string HAUDUSBD { get; set; }
    }
}
