//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORA_ASPNET_PATHS
    {
        public ORA_ASPNET_PATHS()
        {
            this.ORA_ASPNET_PERSONALIZNALLUSERS = new HashSet<ORA_ASPNET_PERSONALIZNALLUSERS>();
            this.ORA_ASPNET_PERSONALIZNPERUSER = new HashSet<ORA_ASPNET_PERSONALIZNPERUSER>();
        }
    
        public System.Guid APPLICATIONID { get; set; }
        public System.Guid PATHID { get; set; }
        public string PATH { get; set; }
        public string LOWEREDPATH { get; set; }
    
        public virtual ORA_ASPNET_APPLICATIONS ORA_ASPNET_APPLICATIONS { get; set; }
        public virtual ICollection<ORA_ASPNET_PERSONALIZNALLUSERS> ORA_ASPNET_PERSONALIZNALLUSERS { get; set; }
        public virtual ICollection<ORA_ASPNET_PERSONALIZNPERUSER> ORA_ASPNET_PERSONALIZNPERUSER { get; set; }
    }
}
