//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAR_IMP
    {
        public string PAR_CIM { get; set; }
        public string PAR_COD { get; set; }
        public string PAR_NOM { get; set; }
        public string PAR_TID { get; set; }
        public string PAR_TAM { get; set; }
        public string PAR_USAP { get; set; }
        public string PAR_USBD { get; set; }
        public Nullable<System.DateTime> PAR_FREG { get; set; }
        public Nullable<System.DateTime> PAR_FNOV { get; set; }
    }
}
