//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECOFICIAL
    {
        public string ROF_CONS { get; set; }
        public string ROF_NIT { get; set; }
        public long ROF_VPA { get; set; }
        public decimal ROF_INT { get; set; }
        public string ROF_COD { get; set; }
        public string ROF_CDEC { get; set; }
        public string ROF_DECC { get; set; }
        public System.DateTime ROF_FNOV { get; set; }
        public string ROF_USBD { get; set; }
        public string ROF_USAP { get; set; }
        public Nullable<System.DateTime> ROF_FREG { get; set; }
        public string ROF_EST { get; set; }
        public Nullable<long> ROF_SAN { get; set; }
        public string ROF_TDOC { get; set; }
        public Nullable<System.DateTime> ROF_FRAD { get; set; }
        public string ROF_TROF { get; set; }
        public Nullable<int> ROF_TPAG { get; set; }
        public string ROF_CTABCO { get; set; }
        public string ROF_BCO { get; set; }
        public string ROF_ANO { get; set; }
        public string ROF_PER { get; set; }
    }
}
