//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REL_INT_MORA
    {
        public string RLIM_NUM { get; set; }
        public string RLIM_DOAD { get; set; }
        public Nullable<decimal> RLIM_VALOR { get; set; }
        public string RLIM_TDOC { get; set; }
        public string RLIM_PER { get; set; }
        public string RLIM_ANO { get; set; }
        public string RLIM_NIT { get; set; }
        public string RLIM_DCOD { get; set; }
        public string RLIM_CDEC { get; set; }
        public string RLIM_USAP { get; set; }
        public string RLIM_USBD { get; set; }
        public System.DateTime RLIM_FREG { get; set; }
    }
}
