//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUI_DECLARACION
    {
        public REQUI_DECLARACION()
        {
            this.DEC_REQUI = new HashSet<DEC_REQUI>();
        }
    
        public string REQ_CLDEC { get; set; }
        public string REQ_COD { get; set; }
        public string REQ_DESC { get; set; }
        public System.DateTime REQ_FINI { get; set; }
        public Nullable<System.DateTime> REQ_FFIN { get; set; }
        public string REQ_USAP { get; set; }
        public string REQ_USBD { get; set; }
        public Nullable<System.DateTime> REQ_FREG { get; set; }
        public Nullable<System.DateTime> REQ_FNOV { get; set; }
    
        public virtual CLASE_DEC CLASE_DEC { get; set; }
        public virtual ICollection<DEC_REQUI> DEC_REQUI { get; set; }
    }
}
