//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECCIONES
    {
        public SECCIONES()
        {
            this.CODE_CDEC = new HashSet<CODE_CDEC>();
            this.CONC_CDEC = new HashSet<CONC_CDEC>();
        }
    
        public string SECC_CODI { get; set; }
        public string SECC_NOMB { get; set; }
        public string SECC_USAP { get; set; }
        public string SECC_USBD { get; set; }
        public Nullable<System.DateTime> SECC_FREG { get; set; }
        public Nullable<System.DateTime> SECC_FNOV { get; set; }
    
        public virtual ICollection<CODE_CDEC> CODE_CDEC { get; set; }
        public virtual ICollection<CONC_CDEC> CONC_CDEC { get; set; }
    }
}
