//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDECLARANTE
    {
        public string TDEC_COD { get; set; }
        public string TDEC_NOMB { get; set; }
        public string TDEC_USAP { get; set; }
        public string TDEC_USBD { get; set; }
        public Nullable<System.DateTime> TDEC_FREG { get; set; }
        public Nullable<System.DateTime> TDEC_FNOV { get; set; }
    }
}
