//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_DEC
    {
        public string TEDE_CODI { get; set; }
        public string TEDE_TNIT { get; set; }
        public string TEDE_CDEC { get; set; }
        public Nullable<System.DateTime> TEDE_FINI { get; set; }
        public Nullable<System.DateTime> TEDE_FFIN { get; set; }
        public string TEDE_USAP { get; set; }
        public string TEDE_USBD { get; set; }
        public Nullable<System.DateTime> TEDE_FREG { get; set; }
        public Nullable<System.DateTime> TEDE_FNOV { get; set; }
    
        public virtual CLASE_DEC CLASE_DEC { get; set; }
    }
}
