//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_DEC
    {
        public string TDEC_COD { get; set; }
        public string TDEC_NOM { get; set; }
        public Nullable<System.DateTime> TDEC_FIN { get; set; }
        public Nullable<System.DateTime> TDEC_FFI { get; set; }
        public string TDEC_USBD { get; set; }
        public string TDEC_USAP { get; set; }
        public System.DateTime TDEC_FREG { get; set; }
        public System.DateTime TDEC_FNOV { get; set; }
        public string TDEC_CDEC { get; set; }
        public string TDEC_CODI { get; set; }
    
        public virtual CLASE_DEC CLASE_DEC { get; set; }
    }
}
