//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_AGENT
    {
        public string TAG_COD { get; set; }
        public string TAG_NOM { get; set; }
        public string TAG_EST { get; set; }
        public string TAG_USAP { get; set; }
        public string TAG_USBD { get; set; }
        public Nullable<System.DateTime> TAG_FREG { get; set; }
        public Nullable<System.DateTime> TAG_FNOV { get; set; }
    }
}
