//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VH_CAPACIDAD_M
    {
        public string GRUPO { get; set; }
        public Nullable<int> DESDE { get; set; }
        public Nullable<int> HASTA { get; set; }
        public string VIG { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
