//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VH_LIQUIDLOG
    {
        public int NRO_LIQG { get; set; }
        public string PLACA { get; set; }
        public string OBSERVACION { get; set; }
        public string LIQUIDO { get; set; }
        public string CATEGORIA_LIQ { get; set; }
        public Nullable<System.DateTime> FECHA_REG { get; set; }
        public string USBD { get; set; }
        public string USAP { get; set; }
        public string VIGENCIALIQ { get; set; }
        public string FILTROVEH { get; set; }
        public string DEC_COD { get; set; }
        public Nullable<int> LIQ_CONS { get; set; }
    }
}
