//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class ACPA_DEUDA
    {
        public string APDE_APNU { get; set; }
        public string APDE_CDEC { get; set; }
        public string APDE_AGRA { get; set; }
        public string APDE_PGRA { get; set; }
        public string APDE_COCO { get; set; }
        public int APDE_VALO { get; set; }
        public string APDE_DOAD { get; set; }
        public string APDE_NDOC { get; set; }
        public System.DateTime APDE_FNOV { get; set; }
        public string APDE_NOMC { get; set; }
        public string APDE_USBD { get; set; }
        public string APDE_USAP { get; set; }
        public System.DateTime APDE_FREG { get; set; }
    
        public virtual CALENDARIO CALENDARIO { get; set; }
        public virtual CONC_CART CONC_CART { get; set; }
        public virtual TIPO_DOC TIPO_DOC { get; set; }
    }
    
}
