//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class ANULACIONES
    {
        public string ANUL_TDAN { get; set; }
        public string ANUL_NDAN { get; set; }
        public string ANUL_TDOC { get; set; }
        public string ANUL_NDOC { get; set; }
        public string ANUL_OBSE { get; set; }
        public Nullable<System.DateTime> ANUL_FREG { get; set; }
        public string ANUL_USAP { get; set; }
        public string ANUL_USBD { get; set; }
        public string ANUL_EST { get; set; }
    }
    
}
