//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class CALENDARIO
    {
        public CALENDARIO()
        {
            this.ACPA_APG = new HashSet<ACPA_APG>();
            this.ACPA_DEUDA = new HashSet<ACPA_DEUDA>();
            this.BASES_LIQ = new HashSet<BASES_LIQ>();
            this.CARTERAD = new HashSet<CARTERAD>();
            this.DECLARACION = new HashSet<DECLARACION>();
            this.DOC_APG = new HashSet<DOC_APG>();
            this.EXPE_APG = new HashSet<EXPE_APG>();
            this.MOVIMIENTO = new HashSet<MOVIMIENTO>();
        }
    
        public string CAL_PER { get; set; }
        public string CAL_VIG { get; set; }
        public System.DateTime CAL_FINI { get; set; }
        public System.DateTime CAL_FFIN { get; set; }
        public string CAL_CLA { get; set; }
        public string CAL_DES { get; set; }
        public string CAL_USBD { get; set; }
        public string CAL_USAP { get; set; }
        public Nullable<System.DateTime> CAL_FREG { get; set; }
        public Nullable<System.DateTime> CAL_FNOV { get; set; }
        public Nullable<System.DateTime> CAL_FVEN { get; set; }
    
        public virtual ICollection<ACPA_APG> ACPA_APG { get; set; }
        public virtual ICollection<ACPA_DEUDA> ACPA_DEUDA { get; set; }
        public virtual ICollection<BASES_LIQ> BASES_LIQ { get; set; }
        public virtual CLASE_DEC CLASE_DEC { get; set; }
        public virtual ICollection<CARTERAD> CARTERAD { get; set; }
        public virtual ICollection<DECLARACION> DECLARACION { get; set; }
        public virtual ICollection<DOC_APG> DOC_APG { get; set; }
        public virtual ICollection<EXPE_APG> EXPE_APG { get; set; }
        public virtual ICollection<MOVIMIENTO> MOVIMIENTO { get; set; }
    }
    
}
