//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class CLD_IMP
    {
        public string CLD_COD { get; set; }
        public string CLD_CIMP { get; set; }
        public string CLD_ABIM { get; set; }
        public string CLD_ABVA { get; set; }
        public Nullable<System.DateTime> CLD_FNOV { get; set; }
        public Nullable<System.DateTime> CLD_FREG { get; set; }
        public string CLD_USAP { get; set; }
        public string CLD_USBD { get; set; }
    
        public virtual CLASE_DEC CLASE_DEC { get; set; }
        public virtual IMPUESTOS IMPUESTOS { get; set; }
    }
    
}
