//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class CONC_CART
    {
        public CONC_CART()
        {
            this.ACPA_DEUDA = new HashSet<ACPA_DEUDA>();
            this.CARTERAD = new HashSet<CARTERAD>();
            this.DIST_CART = new HashSet<DIST_CART>();
        }
    
        public string CCAR_COD { get; set; }
        public string CCAR_AVCO { get; set; }
        public string CCAR_NOM { get; set; }
        public string CCAR_TICO { get; set; }
        public string CCAR_CDEC { get; set; }
        public string CCAR_USAP { get; set; }
        public Nullable<System.DateTime> CCAR_FREG { get; set; }
        public Nullable<System.DateTime> CCAR_FNOV { get; set; }
        public string CCAR_USBD { get; set; }
    
        public virtual ICollection<ACPA_DEUDA> ACPA_DEUDA { get; set; }
        public virtual ICollection<CARTERAD> CARTERAD { get; set; }
        public virtual TIPO_CONCEPTOS TIPO_CONCEPTOS { get; set; }
        public virtual ICollection<DIST_CART> DIST_CART { get; set; }
    }
    
}
