//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class CONC_CDEC
    {
        public string COCD_CDEC { get; set; }
        public string COCD_CODI { get; set; }
        public string COCD_TICO { get; set; }
        public string COCD_NOMB { get; set; }
        public string COCD_REDE { get; set; }
        public string COCD_TMOV { get; set; }
        public string COCD_ABVB { get; set; }
        public Nullable<decimal> COCD_VADE { get; set; }
        public string COCD_ABVD { get; set; }
        public Nullable<int> COCD_VACA { get; set; }
        public string COCD_SECO { get; set; }
        public Nullable<decimal> COCD_TARI { get; set; }
        public string COCD_IMPTO { get; set; }
        public string COCD_TSAN { get; set; }
        public string COCD_CART { get; set; }
        public Nullable<int> COCD_VABA { get; set; }
        public string COCD_ISVB { get; set; }
        public string COCD_OPER { get; set; }
        public string COCD_CCAR { get; set; }
        public string COCD_AÑSA { get; set; }
        public string COCD_PESA { get; set; }
        public string COCD_SUM { get; set; }
        public string COCD_FDCO { get; set; }
        public string COCD_CTAR { get; set; }
        public Nullable<short> TIPO_TAR { get; set; }
        public string COCD_USAP { get; set; }
        public Nullable<System.DateTime> COCD_FREG { get; set; }
        public Nullable<System.DateTime> COCD_FNOV { get; set; }
        public string COCD_USBD { get; set; }
        public Nullable<int> COCD_REVB { get; set; }
        public string FORMULA { get; set; }
    
        public virtual CLASE_DEC CLASE_DEC { get; set; }
        public virtual FORMULARIOS_DEC FORMULARIOS_DEC { get; set; }
        public virtual SECCIONES SECCIONES { get; set; }
    }
    
}
