//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class CONSECUTIVOS
    {
        public string CONS_VIG { get; set; }
        public int CONS_ID { get; set; }
        public string CONS_NOM { get; set; }
        public int CONS_PRX { get; set; }
        public int CONS_INI { get; set; }
        public string CONS_USAP { get; set; }
        public string CONS_USBD { get; set; }
        public Nullable<System.DateTime> CONS_FREG { get; set; }
        public Nullable<System.DateTime> CONS_FNOV { get; set; }
    
        public virtual VIGENCIA VIGENCIA { get; set; }
    }
    
}
