//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class CONT_PERI
    {
        public string COPE_AÑO { get; set; }
        public string COPE_MES { get; set; }
        public string COPE_ESTA { get; set; }
        public System.DateTime COPE_FNOV { get; set; }
        public string COPE_USBD { get; set; }
        public string COPE_USAP { get; set; }
        public Nullable<System.DateTime> COPE_FREG { get; set; }
    }
    
}
