//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class DEC_REQUI
    {
        public string DR_CODDEC { get; set; }
        public string DR_PERI { get; set; }
        public string DR_ANO { get; set; }
        public string DR_CODREQ { get; set; }
        public string DR_ESTADO { get; set; }
        public System.DateTime DR_FECRAD { get; set; }
        public string DR_USBD { get; set; }
        public string DR_USAP { get; set; }
        public Nullable<System.DateTime> DR_FECPRE { get; set; }
        public string DR_FUNC { get; set; }
        public string DR_NRORAD { get; set; }
        public Nullable<System.DateTime> DR_FREG { get; set; }
        public Nullable<System.DateTime> DR_FNOV { get; set; }
        public string DR_CDEC { get; set; }
    
        public virtual REQUI_DECLARACION REQUI_DECLARACION { get; set; }
    }
    
}
