//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class DECLARACION
    {
        public DECLARACION()
        {
            this.CODE_CDEC = new HashSet<CODE_CDEC>();
        }
    
        public string DEC_NRO { get; set; }
        public string DEC_NIT { get; set; }
        public string DEC_PER { get; set; }
        public string DEC_ANO { get; set; }
        public string DEC_VIG { get; set; }
        public string DEC_EST { get; set; }
        public System.DateTime DEC_FREG { get; set; }
        public string DEC_CNRO { get; set; }
        public string DEC_USAP { get; set; }
        public string DEC_USBD { get; set; }
        public int DEC_CONS { get; set; }
        public string DEC_TIP { get; set; }
        public string DEC_SIG_DEC { get; set; }
        public string DEC_SIG_CTRF { get; set; }
        public string DEC_RAZSOC { get; set; }
        public string DEC_SCR_TIP { get; set; }
        public string DEC_SIG_DEC_TDOC { get; set; }
        public string DEC_SIG_CTRF_TDOC { get; set; }
        public string DEC_SIG_CTRF_NOM { get; set; }
        public string DEC_SIG_DEC_NOM { get; set; }
        public string DEC_SIG_CTRF_TAR_PRO { get; set; }
        public string DEC_TDOC { get; set; }
        public string DEC_DVER { get; set; }
        public Nullable<decimal> DEC_TRET { get; set; }
        public decimal DEC_TSAN { get; set; }
        public Nullable<decimal> DEC_TRS { get; set; }
        public Nullable<decimal> DEC_PRS { get; set; }
        public Nullable<decimal> DEC_PIM { get; set; }
        public Nullable<decimal> DEC_PTOT { get; set; }
        public string DEC_CSAN { get; set; }
        public string DEC_CDEC { get; set; }
        public string DEC_EST_FIS { get; set; }
        public Nullable<System.DateTime> DEC_FPRE { get; set; }
        public string DEC_COD { get; set; }
        public string DEC_FDCO { get; set; }
        public Nullable<System.DateTime> DEC_FVEN { get; set; }
        public string DEC_BACO { get; set; }
        public string DEC_CTA { get; set; }
        public string DEC_ROF { get; set; }
        public string DEC_DOAD { get; set; }
        public Nullable<System.DateTime> DEC_FNOV { get; set; }
        public string DEC_ESFI { get; set; }
    
        public virtual CALENDARIO CALENDARIO { get; set; }
        public virtual ICollection<CODE_CDEC> CODE_CDEC { get; set; }
        public virtual FORMULARIOS_DEC FORMULARIOS_DEC { get; set; }
        public virtual TERCEROS TERCEROS { get; set; }
        public virtual TERCEROS TERCEROS1 { get; set; }
        public virtual TERCEROS TERCEROS2 { get; set; }
        public virtual TIPO_DOC TIPO_DOC { get; set; }
        public virtual VIGENCIA VIGENCIA { get; set; }
    }
    
}
