//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class ENTIDAD
    {
        public string ENT_NIT { get; set; }
        public string ENT_NOM { get; set; }
        public string ENT_DIR { get; set; }
        public string ENT_TEL { get; set; }
        public string ENT_EMAIL { get; set; }
        public string ENT_DPTO { get; set; }
        public string ENT_MPIO { get; set; }
        public string ENT_CEDRES { get; set; }
        public string ENT_NOMRES { get; set; }
        public string ENT_LOGO { get; set; }
        public string ENT_USAP { get; set; }
        public string ENT_USBD { get; set; }
        public Nullable<System.DateTime> ENT_FREG { get; set; }
        public Nullable<System.DateTime> ENT_FNOV { get; set; }
    }
    
}
