//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class EXPE_ANULA
    {
        public string EXPE_NUME { get; set; }
        public string EXPE_ID { get; set; }
        public Nullable<System.DateTime> EXPE_FANU { get; set; }
        public string EXPE_OBSE { get; set; }
        public string TABLA { get; set; }
        public string EXPE_USAP { get; set; }
        public string EXPE_USBD { get; set; }
        public System.DateTime EXPE_FREG { get; set; }
    }
    
}
