//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class FORMULARIOS_DEC
    {
        public FORMULARIOS_DEC()
        {
            this.BASES_LIQ = new HashSet<BASES_LIQ>();
            this.CONC_CDEC = new HashSet<CONC_CDEC>();
            this.DECLARACION = new HashSet<DECLARACION>();
            this.DIST_CART = new HashSet<DIST_CART>();
            this.FORM_AYUD = new HashSet<FORM_AYUD>();
        }
    
        public string FODE_CODI { get; set; }
        public string FODE_CDEC { get; set; }
        public string FODE_FOWE { get; set; }
        public string FODE_RPTE { get; set; }
        public System.DateTime FODE_FEIN { get; set; }
        public System.DateTime FODE_FEFI { get; set; }
        public string FODE_USBD { get; set; }
        public System.DateTime FODE_FREG { get; set; }
        public string FODE_USAP { get; set; }
        public string FODE_OPER { get; set; }
        public string FODE_FOWI { get; set; }
        public string FODE_NOMB { get; set; }
        public string FODE_EST { get; set; }
        public string FODE_OPVP { get; set; }
        public Nullable<System.DateTime> FODE_FNOV { get; set; }
        public string FODE_OBS { get; set; }
    
        public virtual ICollection<BASES_LIQ> BASES_LIQ { get; set; }
        public virtual CLASE_DEC CLASE_DEC { get; set; }
        public virtual ICollection<CONC_CDEC> CONC_CDEC { get; set; }
        public virtual ICollection<DECLARACION> DECLARACION { get; set; }
        public virtual ICollection<DIST_CART> DIST_CART { get; set; }
        public virtual ICollection<FORM_AYUD> FORM_AYUD { get; set; }
    }
    
}
