//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class Entities : DbContext
{
    public Entities()
        : base("name=Entities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<ACPA_APG> ACPA_APG { get; set; }
    public DbSet<ACPA_DEUDA> ACPA_DEUDA { get; set; }
    public DbSet<ACUE_PAGO> ACUE_PAGO { get; set; }
    public DbSet<AGENTES> AGENTES { get; set; }
    public DbSet<ANULACIONES> ANULACIONES { get; set; }
    public DbSet<BANCOS> BANCOS { get; set; }
    public DbSet<BASES_LIQ> BASES_LIQ { get; set; }
    public DbSet<CALENDARIO> CALENDARIO { get; set; }
    public DbSet<CARTERAD> CARTERAD { get; set; }
    public DbSet<CLASE_DEC> CLASE_DEC { get; set; }
    public DbSet<CLASE_IMPTO> CLASE_IMPTO { get; set; }
    public DbSet<CLASE_NOTIFICACION> CLASE_NOTIFICACION { get; set; }
    public DbSet<CLD_IMP> CLD_IMP { get; set; }
    public DbSet<CODE_CDEC> CODE_CDEC { get; set; }
    public DbSet<CON_ROF> CON_ROF { get; set; }
    public DbSet<CONC_CART> CONC_CART { get; set; }
    public DbSet<CONC_CDEC> CONC_CDEC { get; set; }
    public DbSet<CONCEPTOS_IMP> CONCEPTOS_IMP { get; set; }
    public DbSet<CONSECUTIVOS> CONSECUTIVOS { get; set; }
    public DbSet<CONT_PERI> CONT_PERI { get; set; }
    public DbSet<COPIAS_RPT> COPIAS_RPT { get; set; }
    public DbSet<CORREOSE> CORREOSE { get; set; }
    public DbSet<CTA_BANCO> CTA_BANCO { get; set; }
    public DbSet<CTRL_PAGOS> CTRL_PAGOS { get; set; }
    public DbSet<CUOT_ACPA> CUOT_ACPA { get; set; }
    public DbSet<DEC_REQUI> DEC_REQUI { get; set; }
    public DbSet<DECLARACION> DECLARACION { get; set; }
    public DbSet<DEPARTAMENTOS> DEPARTAMENTOS { get; set; }
    public DbSet<DIST_CART> DIST_CART { get; set; }
    public DbSet<DOC_APG> DOC_APG { get; set; }
    public DbSet<DPAGO_ROAP> DPAGO_ROAP { get; set; }
    public DbSet<EMPRESA_MENSAJERIA> EMPRESA_MENSAJERIA { get; set; }
    public DbSet<ENTIDAD> ENTIDAD { get; set; }
    public DbSet<ESTADOS> ESTADOS { get; set; }
    public DbSet<EXPE_ANULA> EXPE_ANULA { get; set; }
    public DbSet<EXPE_APG> EXPE_APG { get; set; }
    public DbSet<EXPE_NOTIF> EXPE_NOTIF { get; set; }
    public DbSet<EXPE_TRAM> EXPE_TRAM { get; set; }
    public DbSet<EXPEDIENTES> EXPEDIENTES { get; set; }
    public DbSet<FM_BASESLIQ01> FM_BASESLIQ01 { get; set; }
    public DbSet<FMTO_IMP> FMTO_IMP { get; set; }
    public DbSet<FMTOS> FMTOS { get; set; }
    public DbSet<FORM_AYUD> FORM_AYUD { get; set; }
    public DbSet<FORMULARIOS_DEC> FORMULARIOS_DEC { get; set; }
    public DbSet<FORMULASL> FORMULASL { get; set; }
    public DbSet<FORMULASLT> FORMULASLT { get; set; }
    public DbSet<HAUDITORIA> HAUDITORIA { get; set; }
    public DbSet<IMPUESTOS> IMPUESTOS { get; set; }
    public DbSet<MENU> MENU { get; set; }
    public DbSet<MENU_PERFIL> MENU_PERFIL { get; set; }
    public DbSet<MUNICIPIOS> MUNICIPIOS { get; set; }
    public DbSet<ORA_ASPNET_APPLICATIONS> ORA_ASPNET_APPLICATIONS { get; set; }
    public DbSet<ORA_ASPNET_MEMBERSHIP> ORA_ASPNET_MEMBERSHIP { get; set; }
    public DbSet<ORA_ASPNET_PATHS> ORA_ASPNET_PATHS { get; set; }
    public DbSet<ORA_ASPNET_PERSONALIZNALLUSERS> ORA_ASPNET_PERSONALIZNALLUSERS { get; set; }
    public DbSet<ORA_ASPNET_PERSONALIZNPERUSER> ORA_ASPNET_PERSONALIZNPERUSER { get; set; }
    public DbSet<ORA_ASPNET_PROFILE> ORA_ASPNET_PROFILE { get; set; }
    public DbSet<ORA_ASPNET_ROLES> ORA_ASPNET_ROLES { get; set; }
    public DbSet<ORA_ASPNET_SESSIONAPPLICATIONS> ORA_ASPNET_SESSIONAPPLICATIONS { get; set; }
    public DbSet<ORA_ASPNET_SESSIONS> ORA_ASPNET_SESSIONS { get; set; }
    public DbSet<ORA_ASPNET_SITEMAP> ORA_ASPNET_SITEMAP { get; set; }
    public DbSet<ORA_ASPNET_USERS> ORA_ASPNET_USERS { get; set; }
    public DbSet<PAR_IMP> PAR_IMP { get; set; }
    public DbSet<PAR_LIQ_DET> PAR_LIQ_DET { get; set; }
    public DbSet<PARA_LIQU> PARA_LIQU { get; set; }
    public DbSet<PROC_LOTE> PROC_LOTE { get; set; }
    public DbSet<PROCESOS> PROCESOS { get; set; }
    public DbSet<RECACUERDO> RECACUERDO { get; set; }
    public DbSet<RECOFICIAL> RECOFICIAL { get; set; }
    public DbSet<REL_INT_MORA> REL_INT_MORA { get; set; }
    public DbSet<RELA_AGETER> RELA_AGETER { get; set; }
    public DbSet<REQUI_DECLARACION> REQUI_DECLARACION { get; set; }
    public DbSet<SECCIONES> SECCIONES { get; set; }
    public DbSet<TARIFAS_IMP> TARIFAS_IMP { get; set; }
    public DbSet<TDECLARANTE> TDECLARANTE { get; set; }
    public DbSet<TDOC_IDE> TDOC_IDE { get; set; }
    public DbSet<TER_DEC> TER_DEC { get; set; }
    public DbSet<TERCEROS> TERCEROS { get; set; }
    public DbSet<TIPO_AGENT> TIPO_AGENT { get; set; }
    public DbSet<TIPO_CONCEPTOS> TIPO_CONCEPTOS { get; set; }
    public DbSet<TIPO_CUENTA> TIPO_CUENTA { get; set; }
    public DbSet<TIPO_DATO> TIPO_DATO { get; set; }
    public DbSet<TIPO_DEC> TIPO_DEC { get; set; }
    public DbSet<TIPO_DOC> TIPO_DOC { get; set; }
    public DbSet<TIPO_DOC_CONS> TIPO_DOC_CONS { get; set; }
    public DbSet<TIPO_MOV> TIPO_MOV { get; set; }
    public DbSet<TIPO_PAGO> TIPO_PAGO { get; set; }
    public DbSet<TIPO_PROCESO> TIPO_PROCESO { get; set; }
    public DbSet<TIPO_SANCIONES> TIPO_SANCIONES { get; set; }
    public DbSet<TIPOUSUA> TIPOUSUA { get; set; }
    public DbSet<TRAM_TER> TRAM_TER { get; set; }
    public DbSet<TRAMITES> TRAMITES { get; set; }
    public DbSet<TRAMRELA> TRAMRELA { get; set; }
    public DbSet<UNIDAD> UNIDAD { get; set; }
    public DbSet<USEREXT> USEREXT { get; set; }
    public DbSet<VH_ASEGURADORA> VH_ASEGURADORA { get; set; }
    public DbSet<VH_BG_AUTO_2007> VH_BG_AUTO_2007 { get; set; }
    public DbSet<VH_BG_AUTO_2008> VH_BG_AUTO_2008 { get; set; }
    public DbSet<VH_BG_AUTO_2009> VH_BG_AUTO_2009 { get; set; }
    public DbSet<VH_CAPACIDAD_M> VH_CAPACIDAD_M { get; set; }
    public DbSet<VH_CARGA_LETRA> VH_CARGA_LETRA { get; set; }
    public DbSet<VH_CARROCERIA> VH_CARROCERIA { get; set; }
    public DbSet<VH_CATEGORIA> VH_CATEGORIA { get; set; }
    public DbSet<VH_CLASE_CATEGORIA> VH_CLASE_CATEGORIA { get; set; }
    public DbSet<VH_CLASE_LIQ> VH_CLASE_LIQ { get; set; }
    public DbSet<VH_COLOR> VH_COLOR { get; set; }
    public DbSet<VH_DATOS_LIQ> VH_DATOS_LIQ { get; set; }
    public DbSet<VH_INSTITUTO_TRANSITO> VH_INSTITUTO_TRANSITO { get; set; }
    public DbSet<VH_LINEA> VH_LINEA { get; set; }
    public DbSet<VH_LIQ_GRUPAL> VH_LIQ_GRUPAL { get; set; }
    public DbSet<VH_LIQUIDLOG> VH_LIQUIDLOG { get; set; }
    public DbSet<VH_MARCA_M> VH_MARCA_M { get; set; }
    public DbSet<VH_PARQUE_AUTOMOTOR> VH_PARQUE_AUTOMOTOR { get; set; }
    public DbSet<VH_PASAJERO_CAP> VH_PASAJERO_CAP { get; set; }
    public DbSet<VIGENCIA> VIGENCIA { get; set; }
    public DbSet<MOVIMIENTO> MOVIMIENTO { get; set; }
    public DbSet<PAGOS> PAGOS { get; set; }
}
