//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class ORA_ASPNET_USERS
    {
        public ORA_ASPNET_USERS()
        {
            this.ORA_ASPNET_PERSONALIZNPERUSER = new HashSet<ORA_ASPNET_PERSONALIZNPERUSER>();
            this.ORA_ASPNET_ROLES = new HashSet<ORA_ASPNET_ROLES>();
        }
    
        public System.Guid APPLICATIONID { get; set; }
        public System.Guid USERID { get; set; }
        public string USERNAME { get; set; }
        public string LOWEREDUSERNAME { get; set; }
        public string MOBILEALIAS { get; set; }
        public decimal ISANONYMOUS { get; set; }
        public System.DateTime LASTACTIVITYDATE { get; set; }
    
        public virtual ORA_ASPNET_APPLICATIONS ORA_ASPNET_APPLICATIONS { get; set; }
        public virtual ORA_ASPNET_MEMBERSHIP ORA_ASPNET_MEMBERSHIP { get; set; }
        public virtual ICollection<ORA_ASPNET_PERSONALIZNPERUSER> ORA_ASPNET_PERSONALIZNPERUSER { get; set; }
        public virtual ORA_ASPNET_PROFILE ORA_ASPNET_PROFILE { get; set; }
        public virtual ICollection<ORA_ASPNET_ROLES> ORA_ASPNET_ROLES { get; set; }
    }
    
}
