//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class PAGOS
    {
        public string PAG_CDEC { get; set; }
        public string PAG_TDOC { get; set; }
        public string PAG_NDOC { get; set; }
        public string PAG_ANO { get; set; }
        public string PAG_PER { get; set; }
        public decimal PAG_TOT { get; set; }
        public System.DateTime PAG_FPAG { get; set; }
        public string PAG_EST { get; set; }
        public Nullable<decimal> PAG_SALD { get; set; }
        public string PAG_USAP { get; set; }
        public string PAG_USBD { get; set; }
        public System.DateTime PAG_FREG { get; set; }
        public string PAG_CTAB { get; set; }
        public string PAG_BACO { get; set; }
        public string PAG_NIT { get; set; }
        public int PAG_ID { get; set; }
        public Nullable<System.DateTime> PAG_FNOV { get; set; }
    
        public virtual CTA_BANCO CTA_BANCO { get; set; }
        public virtual TIPO_DOC TIPO_DOC { get; set; }
    }
    
}
