//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class PARA_LIQU
    {
        public PARA_LIQU()
        {
            this.PAR_LIQ_DET = new HashSet<PAR_LIQ_DET>();
        }
    
        public string PALI_CODI { get; set; }
        public string PALI_NOMB { get; set; }
        public string PALI_TIDA { get; set; }
        public string PALI_VARI { get; set; }
        public string PALI_ESTA { get; set; }
        public string PALI_DESC { get; set; }
        public string PALI_USAP { get; set; }
        public string PALI_USBD { get; set; }
        public Nullable<System.DateTime> PALI_FREG { get; set; }
        public Nullable<System.DateTime> PALI_FNOV { get; set; }
    
        public virtual ICollection<PAR_LIQ_DET> PAR_LIQ_DET { get; set; }
        public virtual TIPO_DATO TIPO_DATO { get; set; }
    }
    
}
