//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class TDECLARANTE
    {
        public string TDEC_COD { get; set; }
        public string TDEC_NOMB { get; set; }
        public string TDEC_USAP { get; set; }
        public string TDEC_USBD { get; set; }
        public Nullable<System.DateTime> TDEC_FREG { get; set; }
        public Nullable<System.DateTime> TDEC_FNOV { get; set; }
    }
    
}
