//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class TER_DEC
    {
        public string TEDE_CODI { get; set; }
        public string TEDE_TNIT { get; set; }
        public string TEDE_CDEC { get; set; }
        public Nullable<System.DateTime> TEDE_FINI { get; set; }
        public Nullable<System.DateTime> TEDE_FFIN { get; set; }
        public string TEDE_USAP { get; set; }
        public string TEDE_USBD { get; set; }
        public Nullable<System.DateTime> TEDE_FREG { get; set; }
        public Nullable<System.DateTime> TEDE_FNOV { get; set; }
    
        public virtual CLASE_DEC CLASE_DEC { get; set; }
    }
    
}
