//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class TIPO_DATO
    {
        public TIPO_DATO()
        {
            this.FMTO_IMP = new HashSet<FMTO_IMP>();
            this.PARA_LIQU = new HashSet<PARA_LIQU>();
        }
    
        public string TIDA_CODI { get; set; }
        public string TIDA_ORACLE { get; set; }
        public string TIDA_NET { get; set; }
        public string TIDA_USAP { get; set; }
        public string TIDA_USBD { get; set; }
        public System.DateTime TIDA_FREG { get; set; }
        public System.DateTime TIDA_FNOV { get; set; }
    
        public virtual ICollection<FMTO_IMP> FMTO_IMP { get; set; }
        public virtual ICollection<PARA_LIQU> PARA_LIQU { get; set; }
    }
    
}
