//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class TIPO_PROCESO
    {
        public TIPO_PROCESO()
        {
            this.EXPEDIENTES = new HashSet<EXPEDIENTES>();
            this.PROCESOS = new HashSet<PROCESOS>();
        }
    
        public string TPRO_CODI { get; set; }
        public string TPRO_NOMB { get; set; }
        public string TPRO_USAP { get; set; }
        public string TPRO_USBD { get; set; }
        public Nullable<System.DateTime> TPRO_FREG { get; set; }
        public Nullable<System.DateTime> TPRO_FNOV { get; set; }
    
        public virtual ICollection<EXPEDIENTES> EXPEDIENTES { get; set; }
        public virtual ICollection<PROCESOS> PROCESOS { get; set; }
    }
    
}
