//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class TIPOUSUA
    {
        public string TUS_COD { get; set; }
        public string TUS_NOM { get; set; }
        public string TUS_USAP { get; set; }
        public string TUS_USBD { get; set; }
        public Nullable<System.DateTime> TUS_FREG { get; set; }
        public Nullable<System.DateTime> TUS_FNOV { get; set; }
    }
    
}
