//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class TIPO_SANCIONES
    {
        public string TSAN_COD { get; set; }
        public string TSAN_NOM { get; set; }
        public string TSAN_FORM { get; set; }
        public string TSAN_PAR { get; set; }
        public string TSAN_DEC { get; set; }
        public string TSAN_DETI { get; set; }
        public string TSAN_USAP { get; set; }
        public string TSAN_USBD { get; set; }
        public Nullable<System.DateTime> TSAN_FREG { get; set; }
        public Nullable<System.DateTime> TSAN_FNOV { get; set; }
    }
    
}
