//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class TIPO_DOC
    {
        public TIPO_DOC()
        {
            this.ACPA_DEUDA = new HashSet<ACPA_DEUDA>();
            this.CARTERAD = new HashSet<CARTERAD>();
            this.CODE_CDEC = new HashSet<CODE_CDEC>();
            this.DECLARACION = new HashSet<DECLARACION>();
            this.DOC_APG = new HashSet<DOC_APG>();
            this.EXPE_APG = new HashSet<EXPE_APG>();
            this.EXPEDIENTES = new HashSet<EXPEDIENTES>();
            this.TIPO_DOC_CONS = new HashSet<TIPO_DOC_CONS>();
            this.MOVIMIENTO = new HashSet<MOVIMIENTO>();
            this.PAGOS = new HashSet<PAGOS>();
        }
    
        public string TIDO_CODI { get; set; }
        public string TIDO_NOMB { get; set; }
        public string TIDO_EST { get; set; }
        public string TIDO_USAP { get; set; }
        public string TIDO_USBD { get; set; }
        public Nullable<System.DateTime> TIDO_FREG { get; set; }
        public Nullable<System.DateTime> TIDO_FNOV { get; set; }
        public byte[] TIDO_FIRMA { get; set; }
        public string TIDO_RESP { get; set; }
    
        public virtual ICollection<ACPA_DEUDA> ACPA_DEUDA { get; set; }
        public virtual ICollection<CARTERAD> CARTERAD { get; set; }
        public virtual ICollection<CODE_CDEC> CODE_CDEC { get; set; }
        public virtual ICollection<DECLARACION> DECLARACION { get; set; }
        public virtual ICollection<DOC_APG> DOC_APG { get; set; }
        public virtual ICollection<EXPE_APG> EXPE_APG { get; set; }
        public virtual ICollection<EXPEDIENTES> EXPEDIENTES { get; set; }
        public virtual ICollection<TIPO_DOC_CONS> TIPO_DOC_CONS { get; set; }
        public virtual ICollection<MOVIMIENTO> MOVIMIENTO { get; set; }
        public virtual ICollection<PAGOS> PAGOS { get; set; }
    }
    
}
