//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class TIPO_PAGO
    {
        public string TPAG_COD { get; set; }
        public string TPAG_NOM { get; set; }
        public string TPAG_USAP { get; set; }
        public string TPAG_USBD { get; set; }
        public Nullable<System.DateTime> TPAG_FREG { get; set; }
        public Nullable<System.DateTime> TPAG_FNOV { get; set; }
    }
    
}
