//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class TRAMITES
    {
        public TRAMITES()
        {
            this.EXPEDIENTES = new HashSet<EXPEDIENTES>();
        }
    
        public string TRAM_CODI { get; set; }
        public string TRAM_NOMB { get; set; }
        public string TRAM_RESP { get; set; }
        public string TRAM_GSAN { get; set; }
        public string TRAM_COSA { get; set; }
        public string TRAM_PLAN { get; set; }
        public string TRAM_USAP { get; set; }
        public string TRAM_USBD { get; set; }
        public Nullable<System.DateTime> TRAM_FREG { get; set; }
        public Nullable<System.DateTime> TRAM_FNOV { get; set; }
        public string TRAM_PROC { get; set; }
        public string TRAM_TIDO { get; set; }
        public string TRAM_AUTO { get; set; }
        public Nullable<short> TRAM_DIAS { get; set; }
        public string TRAM_TIPO { get; set; }
        public string TRAM_VFREB { get; set; }
        public string TRAM_TPRO { get; set; }
    
        public virtual ICollection<EXPEDIENTES> EXPEDIENTES { get; set; }
    }
    
}
