//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class TRAMRELA
    {
        public string TRRE_DESD { get; set; }
        public string TRRE_PARA { get; set; }
        public short TRRE_DILI { get; set; }
        public string TRRE_USAP { get; set; }
        public string TRRE_USBD { get; set; }
        public Nullable<System.DateTime> TRRE_FREG { get; set; }
        public Nullable<System.DateTime> TRRE_FNOV { get; set; }
    }
    
}
