//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class VH_COLOR
    {
        public string NOM_COLOR { get; set; }
        public Nullable<decimal> ID_VH_COLOR { get; set; }
    }
    
}
