//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class VH_DATOS_LIQ
    {
        public string DECCOD { get; set; }
        public string PLACA { get; set; }
        public string CLASE { get; set; }
        public string MARCA { get; set; }
        public string LINEA { get; set; }
        public string MODELO { get; set; }
        public string COLOR { get; set; }
        public string CARROCERIA { get; set; }
        public Nullable<int> CILINDRAJE { get; set; }
        public Nullable<int> TONELAJE { get; set; }
        public Nullable<int> PASAJEROS { get; set; }
        public string MOTOR { get; set; }
        public string CHASIS { get; set; }
        public string BLINDADO { get; set; }
        public string ANTIGUO { get; set; }
        public string NIT { get; set; }
        public Nullable<System.DateTime> FECHA_COMPRA { get; set; }
        public string MUN_MATRICULA { get; set; }
        public string MUN_OPERACION { get; set; }
        public Nullable<System.DateTime> FECHA_MAT { get; set; }
        public string TIPO_MATRICULA { get; set; }
        public string COD_ASEGURADORA { get; set; }
        public string N_POLIZA { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO { get; set; }
        public Nullable<decimal> CONS { get; set; }
        public Nullable<System.DateTime> FEC_LIQ { get; set; }
        public string ESTADO { get; set; }
        public Nullable<decimal> AVALUO { get; set; }
        public Nullable<decimal> TARIFA { get; set; }
        public string DSC_MAT_TRA { get; set; }
        public Nullable<short> FRACCION { get; set; }
        public Nullable<decimal> DEC_STOT { get; set; }
        public string NOM_ASEGURADORA { get; set; }
        public Nullable<int> NRO_LIQG { get; set; }
    }
    
}
