//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class VH_MARCA_M
    {
        public string GRUPO { get; set; }
        public string MARCA { get; set; }
        public string VIG { get; set; }
        public string MARCA_H { get; set; }
    }
    
}
