//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class VH_PARQUE_AUTOMOTOR
    {
        public string PLACA { get; set; }
        public string CLASE { get; set; }
        public string MARCA { get; set; }
        public string LINEA { get; set; }
        public string MODELO { get; set; }
        public string COLOR { get; set; }
        public string CARROCERIA { get; set; }
        public Nullable<int> CILINDRAJE { get; set; }
        public Nullable<int> TONELAJE { get; set; }
        public Nullable<int> PASAJEROS { get; set; }
        public string MOTOR { get; set; }
        public string CHASIS { get; set; }
        public string BLINDADO { get; set; }
        public string ANTIGUO { get; set; }
        public string NIT { get; set; }
        public Nullable<System.DateTime> FECHA_COMPRA { get; set; }
        public string MUN_MATRICULA { get; set; }
        public string MUN_OPERACION { get; set; }
        public Nullable<System.DateTime> FECHA_MAT { get; set; }
        public string TIPO_MATRICULA { get; set; }
        public Nullable<decimal> VALOR_FACT { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        public string PARQ_USAP { get; set; }
        public string PARQ_USBD { get; set; }
        public Nullable<System.DateTime> PARQ_FREG { get; set; }
        public Nullable<System.DateTime> FEC_EXP_TP { get; set; }
        public string VINS_CODIGO { get; set; }
        public string IMPORTADO { get; set; }
        public string USO { get; set; }
        public string CATEGORIA { get; set; }
    }
    
}
