//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class VIGENCIA
    {
        public VIGENCIA()
        {
            this.CODE_CDEC = new HashSet<CODE_CDEC>();
            this.CONSECUTIVOS = new HashSet<CONSECUTIVOS>();
            this.DECLARACION = new HashSet<DECLARACION>();
        }
    
        public string VIG_COD { get; set; }
        public System.DateTime VIG_FINI { get; set; }
        public Nullable<System.DateTime> VIG_FFIN { get; set; }
        public string VIG_EST { get; set; }
        public string VIG_USAP { get; set; }
        public string VIG_USBD { get; set; }
        public Nullable<System.DateTime> VIG_FREG { get; set; }
        public Nullable<System.DateTime> VIG_FNOV { get; set; }
    
        public virtual ICollection<CODE_CDEC> CODE_CDEC { get; set; }
        public virtual ICollection<CONSECUTIVOS> CONSECUTIVOS { get; set; }
        public virtual ICollection<DECLARACION> DECLARACION { get; set; }
        public virtual ESTADOS ESTADOS { get; set; }
    }
    
}
