//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class AGENTES
    {
        public string AGE_NIT { get; set; }
        public string AGE_NOM { get; set; }
        public string AGE_TIP { get; set; }
        public string AGE_MPIO { get; set; }
        public string AGE_EMAI { get; set; }
        public string AGE_TEL { get; set; }
        public string AGE_DIR { get; set; }
        public string AGE_CED { get; set; }
        public string AGE_REP { get; set; }
        public string AGE_USU { get; set; }
        public System.DateTime AGE_FREG { get; set; }
        public Nullable<System.DateTime> AGE_FNOV { get; set; }
        public string AGE_EST { get; set; }
        public string AGE_OBS { get; set; }
        public Nullable<System.DateTime> AGE_FFIN { get; set; }
        public string AGE_USAP { get; set; }
        public string AGE_USBD { get; set; }
        public Nullable<int> AGE_CONS { get; set; }
    }
    
}
