//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class BASES_LIQ
    {
        public BASES_LIQ()
        {
            this.FM_BASESLIQ01 = new HashSet<FM_BASESLIQ01>();
        }
    
        public int BALI_NRAD { get; set; }
        public string BALI_NIT { get; set; }
        public string BALI_CDEC { get; set; }
        public string BALI_AÑO { get; set; }
        public string BALI_PERI { get; set; }
        public string BALI_ARCH { get; set; }
        public string BALI_EST { get; set; }
        public string BALI_USAP { get; set; }
        public string BALI_USBD { get; set; }
        public Nullable<System.DateTime> BALI_FESI { get; set; }
        public Nullable<System.DateTime> BALI_FECH { get; set; }
        public string BALI_FDCO { get; set; }
        public Nullable<System.DateTime> BALI_FREG { get; set; }
        public Nullable<System.DateTime> BALI_FNOV { get; set; }
    
        public virtual CALENDARIO CALENDARIO { get; set; }
        public virtual FORMULARIOS_DEC FORMULARIOS_DEC { get; set; }
        public virtual ICollection<FM_BASESLIQ01> FM_BASESLIQ01 { get; set; }
    }
    
}
