//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class CLASE_IMPTO
    {
        public string CLIM_CODI { get; set; }
        public string CLIM_NOMB { get; set; }
        public Nullable<System.DateTime> CLIM_FEIN { get; set; }
        public Nullable<System.DateTime> CLIM_FEFI { get; set; }
        public string CLIM_USBD { get; set; }
        public Nullable<System.DateTime> CLIM_FNOV { get; set; }
        public Nullable<System.DateTime> CLIM_FREG { get; set; }
        public string CLIM_USAP { get; set; }
    }
    
}
