//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class CON_ROF
    {
        public string CORP_CDEC { get; set; }
        public string CORP_CODI { get; set; }
        public string CORP_TICO { get; set; }
        public string CORP_NOMB { get; set; }
        public string CORP_TMOV { get; set; }
        public string CORP_ABVB { get; set; }
        public Nullable<int> CORP_VADE { get; set; }
        public string CORP_ABVD { get; set; }
        public Nullable<int> CORP_VACA { get; set; }
        public string CORP_SECO { get; set; }
        public Nullable<decimal> CORP_TARI { get; set; }
        public string CORP_IMPTO { get; set; }
        public string CORP_TSAN { get; set; }
        public string CORP_CART { get; set; }
        public Nullable<int> CORP_VABA { get; set; }
        public string CORP_ISVB { get; set; }
        public string CORP_REDE { get; set; }
        public string CORP_DENR { get; set; }
        public int CORP_VASU { get; set; }
        public Nullable<int> CORP_VAOF { get; set; }
        public string CORP_USBD { get; set; }
        public string CORP_USAP { get; set; }
        public string CORP_DEES { get; set; }
        public Nullable<System.DateTime> CORP_FREG { get; set; }
        public string CORP_PESA { get; set; }
        public string CORP_AÑSA { get; set; }
        public string CORP_CCAR { get; set; }
        public string CORP_SUM { get; set; }
        public string CORP_DCOD { get; set; }
        public string CORP_VIG { get; set; }
        public string CORP_DOAD { get; set; }
        public string CORP_CTAR { get; set; }
        public Nullable<System.DateTime> CORP_FNOV { get; set; }
        public Nullable<long> CORP_VBCA { get; set; }
        public Nullable<decimal> CORP_TACA { get; set; }
    }
    
}
