//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class CONCEPTOS_IMP
    {
        public string COIM_CIMP { get; set; }
        public string COIM_COD { get; set; }
        public string COIM_NOM { get; set; }
        public string COIM_TARIFA { get; set; }
        public Nullable<System.DateTime> COIM_FNOV { get; set; }
        public string COIM_EST { get; set; }
        public string COIM_PRI { get; set; }
        public string COIM_TCON { get; set; }
        public string COIM_TMOV { get; set; }
        public Nullable<decimal> COIM_IDX { get; set; }
        public string COIM_USBD { get; set; }
        public string COIM_USAP { get; set; }
        public Nullable<System.DateTime> COIM_FREG { get; set; }
    }
    
}
