//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class COPIAS_RPT
    {
        public string COP_COD { get; set; }
        public string COP_NOM { get; set; }
        public string COP_USAP { get; set; }
        public string COP_USBD { get; set; }
        public Nullable<System.DateTime> COP_FREG { get; set; }
        public Nullable<System.DateTime> COP_FNOV { get; set; }
    }
    
}
