//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class CTA_BANCO
    {
        public CTA_BANCO()
        {
            this.PAGOS = new HashSet<PAGOS>();
        }
    
        public string CTA_BACO { get; set; }
        public string CTA_NRO { get; set; }
        public string CTA_TIP { get; set; }
        public string CTA_CODBAR { get; set; }
        public string CTA_EST { get; set; }
        public string CTA_USAP { get; set; }
        public string CTA_USBD { get; set; }
        public string CTA_DESC { get; set; }
        public string CTA_SUC { get; set; }
        public Nullable<System.DateTime> CTA_FREG { get; set; }
        public Nullable<System.DateTime> CTA_FNOV { get; set; }
    
        public virtual BANCOS BANCOS { get; set; }
        public virtual TIPO_CUENTA TIPO_CUENTA { get; set; }
        public virtual ICollection<PAGOS> PAGOS { get; set; }
    }
    
}
