//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class CTRL_PAGOS
    {
        public string NUM_LOTE { get; set; }
        public Nullable<System.DateTime> FECHA_SUBIDA { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string USBD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string USAP { get; set; }
        public decimal ID { get; set; }
        public byte[] DOCUMENTO { get; set; }
    }
    
}
