//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class CUOT_ACPA
    {
        public string CUAP_APNU { get; set; }
        public int CUAP_CUNU { get; set; }
        public int CUAP_VALO { get; set; }
        public int CUAP_PAGO { get; set; }
        public System.DateTime CUAP_FEPA { get; set; }
        public System.DateTime CUAP_FREG { get; set; }
        public string CUAP_USBD { get; set; }
        public string CUAP_USAP { get; set; }
        public Nullable<System.DateTime> CUAP_FNOV { get; set; }
    
        public virtual ACUE_PAGO ACUE_PAGO { get; set; }
    }
    
}
