//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class DIST_CART
    {
        public string DICA_CDEC { get; set; }
        public string DICA_CODD { get; set; }
        public string DICA_CODC { get; set; }
        public string DICA_FDCO { get; set; }
        public Nullable<short> DICA_ORDE { get; set; }
        public string DICA_USAP { get; set; }
        public string DICA_USBD { get; set; }
        public Nullable<System.DateTime> DICA_FREG { get; set; }
        public Nullable<System.DateTime> DICA_FNOV { get; set; }
    
        public virtual CLASE_DEC CLASE_DEC { get; set; }
        public virtual CONC_CART CONC_CART { get; set; }
        public virtual FORMULARIOS_DEC FORMULARIOS_DEC { get; set; }
    }
    
}
