//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class DOC_APG
    {
        public string DAPG_NIT { get; set; }
        public string DAPG_CDEC { get; set; }
        public string DAPG_AÑO { get; set; }
        public string DAPG_PER { get; set; }
        public System.DateTime DAPG_FELA { get; set; }
        public Nullable<System.DateTime> DAPG_FNOT { get; set; }
        public string DAPG_ESTA { get; set; }
        public string DAPG_USBD { get; set; }
        public string DAPG_USAP { get; set; }
        public System.DateTime DAPG_FREG { get; set; }
        public string DAPG_DOAD { get; set; }
        public string DAPG_DCOD { get; set; }
    
        public virtual CALENDARIO CALENDARIO { get; set; }
        public virtual TIPO_DOC TIPO_DOC { get; set; }
    }
    
}
