//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class DPAGO_ROAP
    {
        public string DPAP_APNU { get; set; }
        public int DPAP_CUNU { get; set; }
        public int DPAP_PAGO { get; set; }
        public System.DateTime DPAP_FEPA { get; set; }
        public System.DateTime DPAP_FREG { get; set; }
        public string DPAP_USBD { get; set; }
        public string DPAP_USAP { get; set; }
        public Nullable<System.DateTime> DPAP_FNOV { get; set; }
        public string DPAP_RNUM { get; set; }
    }
    
}
