//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class EXPE_NOTIF
    {
        public decimal EXNF_ID { get; set; }
        public Nullable<System.DateTime> EXNF_FREB { get; set; }
        public string EXNF_NOTIF { get; set; }
        public string EXNF_MEDIO { get; set; }
        public Nullable<System.DateTime> EXNF_FENV { get; set; }
        public string EXNF_REC { get; set; }
        public string EXNF_OBS { get; set; }
        public string EXNF_EMM { get; set; }
        public string EXTR_NUME { get; set; }
        public string EXTR_TRAC { get; set; }
        public string EXTR_GUIA { get; set; }
        public string EXTR_USAP { get; set; }
        public string EXTR_USBD { get; set; }
        public System.DateTime EXTR_FREG { get; set; }
    
        public virtual EXPEDIENTES EXPEDIENTES { get; set; }
    }
    
}
