//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class EXPE_APG
    {
        public string EXAP_NUME { get; set; }
        public string EXAP_DOAD { get; set; }
        public string EXAP_AGRA { get; set; }
        public string EXAP_PGRA { get; set; }
        public string EXAP_ESTA { get; set; }
        public string EXPE_USBD { get; set; }
        public string EXPE_USAP { get; set; }
        public System.DateTime EXPE_FREG { get; set; }
        public string EXAP_OBSE { get; set; }
        public string EXPE_CDEC { get; set; }
        public string EXAP_EXPR { get; set; }
        public string EXAP_SUIM { get; set; }
        public string EXAP_DCOD { get; set; }
    
        public virtual CALENDARIO CALENDARIO { get; set; }
        public virtual EXPEDIENTES EXPEDIENTES { get; set; }
        public virtual TIPO_DOC TIPO_DOC { get; set; }
    }
    
}
