//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class FMTOS
    {
        public FMTOS()
        {
            this.FMTO_IMP = new HashSet<FMTO_IMP>();
        }
    
        public string FMTO_CODI { get; set; }
        public string FMTO_NOMB { get; set; }
        public string FMTO_DESC { get; set; }
        public string FMTO_CDEC { get; set; }
        public string FMTO_EST { get; set; }
        public string FMTO_USAP { get; set; }
        public string FMTO_USBD { get; set; }
        public Nullable<System.DateTime> FMTO_FREG { get; set; }
        public Nullable<System.DateTime> FMTO_FNOV { get; set; }
    
        public virtual ICollection<FMTO_IMP> FMTO_IMP { get; set; }
    }
    
}
