//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class FMTO_IMP
    {
        public string FMIM_CAMP { get; set; }
        public string FMIM_TIDA { get; set; }
        public string FMIM_CODI { get; set; }
        public short FMIM_INDX { get; set; }
        public string FMIM_LONG { get; set; }
        public string FMIM_USAP { get; set; }
        public string FMIM_USBD { get; set; }
        public Nullable<System.DateTime> FMIM_FREG { get; set; }
        public Nullable<System.DateTime> FMIM_FNOV { get; set; }
        public string FMIM_EST { get; set; }
    
        public virtual TIPO_DATO TIPO_DATO { get; set; }
        public virtual FMTOS FMTOS { get; set; }
    }
    
}
