//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class FORM_AYUD
    {
        public string FOAY_CODI { get; set; }
        public Nullable<short> FOAY_NREN { get; set; }
        public string FOAY_FDCO { get; set; }
        public string FOAY_TITU { get; set; }
        public string FOAY_DESC { get; set; }
        public string FOAY_USAP { get; set; }
        public string FOAY_USBD { get; set; }
        public Nullable<System.DateTime> FOAY_FREG { get; set; }
        public Nullable<System.DateTime> FOAY_FNOV { get; set; }
    
        public virtual FORMULARIOS_DEC FORMULARIOS_DEC { get; set; }
    }
    
}
