//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class FORMULASL
    {
        public string FORM_CODI { get; set; }
        public System.DateTime FORM_FEIN { get; set; }
        public System.DateTime FORM_FEFI { get; set; }
        public string FORM_FORM { get; set; }
        public string FORM_NORM { get; set; }
        public string FORM_CONC { get; set; }
        public string FORM_USAP { get; set; }
        public string FORM_USBD { get; set; }
        public Nullable<System.DateTime> FORM_FREG { get; set; }
        public Nullable<System.DateTime> FORM_FNOV { get; set; }
    }
    
}
