//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ACPA_APG
{
    public string APG_APNU { get; set; }
    public string APG_CDEC { get; set; }
    public string APG_AGRA { get; set; }
    public string APG_PGRA { get; set; }
    public System.DateTime APG_FNOV { get; set; }
    public string APG_USBD { get; set; }
    public string APG_USAP { get; set; }
    public System.DateTime APG_FREG { get; set; }

    public virtual ACUE_PAGO ACUE_PAGO { get; set; }
    public virtual CALENDARIO CALENDARIO { get; set; }
}

public partial class ACPA_DEUDA
{
    public string APDE_APNU { get; set; }
    public string APDE_CDEC { get; set; }
    public string APDE_AGRA { get; set; }
    public string APDE_PGRA { get; set; }
    public string APDE_COCO { get; set; }
    public int APDE_VALO { get; set; }
    public string APDE_DOAD { get; set; }
    public string APDE_NDOC { get; set; }
    public System.DateTime APDE_FNOV { get; set; }
    public string APDE_NOMC { get; set; }
    public string APDE_USBD { get; set; }
    public string APDE_USAP { get; set; }
    public System.DateTime APDE_FREG { get; set; }

    public virtual CALENDARIO CALENDARIO { get; set; }
    public virtual CONC_CART CONC_CART { get; set; }
    public virtual TIPO_DOC TIPO_DOC { get; set; }
}

public partial class ACUE_PAGO
{
    public ACUE_PAGO()
    {
        this.ACPA_APG = new HashSet<ACPA_APG>();
        this.CUOT_ACPA = new HashSet<CUOT_ACPA>();
    }

    public string ACPA_CDEC { get; set; }
    public string ACPA_NUME { get; set; }
    public string ACPA_NIT_AR { get; set; }
    public string ACPA_TIP_AR { get; set; }
    public string ACPA_REP_LEG { get; set; }
    public string ACPA_NIT_REP_LEG { get; set; }
    public string ACPA_REP_EXP { get; set; }
    public string ACPA_GARA { get; set; }
    public string ACPA_USBD { get; set; }
    public string ACPA_USAP { get; set; }
    public System.DateTime ACPA_FREG { get; set; }
    public int ACPA_VALO { get; set; }
    public Nullable<decimal> ACPA_POCI { get; set; }
    public Nullable<int> ACPA_VACI { get; set; }
    public int ACPA_NCUO { get; set; }
    public Nullable<System.DateTime> ACPA_FNOV { get; set; }
    public Nullable<int> ACPA_SALD { get; set; }
    public string ACPA_EST { get; set; }
    public string ACPA_NEXP { get; set; }

    public virtual ICollection<ACPA_APG> ACPA_APG { get; set; }
    public virtual CLASE_DEC CLASE_DEC { get; set; }
    public virtual TERCEROS TERCEROS { get; set; }
    public virtual ICollection<CUOT_ACPA> CUOT_ACPA { get; set; }
}

public partial class AGENTES
{
    public string AGE_NIT { get; set; }
    public string AGE_NOM { get; set; }
    public string AGE_TIP { get; set; }
    public string AGE_MPIO { get; set; }
    public string AGE_EMAI { get; set; }
    public string AGE_TEL { get; set; }
    public string AGE_DIR { get; set; }
    public string AGE_CED { get; set; }
    public string AGE_REP { get; set; }
    public string AGE_USU { get; set; }
    public System.DateTime AGE_FREG { get; set; }
    public Nullable<System.DateTime> AGE_FNOV { get; set; }
    public string AGE_EST { get; set; }
    public string AGE_OBS { get; set; }
    public Nullable<System.DateTime> AGE_FFIN { get; set; }
    public string AGE_USAP { get; set; }
    public string AGE_USBD { get; set; }
    public Nullable<int> AGE_CONS { get; set; }
}

public partial class ANULACIONES
{
    public string ANUL_TDAN { get; set; }
    public string ANUL_NDAN { get; set; }
    public string ANUL_TDOC { get; set; }
    public string ANUL_NDOC { get; set; }
    public string ANUL_OBSE { get; set; }
    public Nullable<System.DateTime> ANUL_FREG { get; set; }
    public string ANUL_USAP { get; set; }
    public string ANUL_USBD { get; set; }
    public string ANUL_EST { get; set; }
}

public partial class BANCOS
{
    public BANCOS()
    {
        this.CTA_BANCO = new HashSet<CTA_BANCO>();
    }

    public string BAN_COD { get; set; }
    public string BAN_NOM { get; set; }
    public string BAN_USAP { get; set; }
    public string BAN_USBD { get; set; }
    public string BAN_EST { get; set; }
    public Nullable<System.DateTime> BAN_FREG { get; set; }
    public Nullable<System.DateTime> BAN_FNOV { get; set; }

    public virtual ICollection<CTA_BANCO> CTA_BANCO { get; set; }
}

public partial class BASES_LIQ
{
    public BASES_LIQ()
    {
        this.FM_BASESLIQ01 = new HashSet<FM_BASESLIQ01>();
    }

    public int BALI_NRAD { get; set; }
    public string BALI_NIT { get; set; }
    public string BALI_CDEC { get; set; }
    public string BALI_AÑO { get; set; }
    public string BALI_PERI { get; set; }
    public string BALI_ARCH { get; set; }
    public string BALI_EST { get; set; }
    public string BALI_USAP { get; set; }
    public string BALI_USBD { get; set; }
    public Nullable<System.DateTime> BALI_FESI { get; set; }
    public Nullable<System.DateTime> BALI_FECH { get; set; }
    public string BALI_FDCO { get; set; }
    public Nullable<System.DateTime> BALI_FREG { get; set; }
    public Nullable<System.DateTime> BALI_FNOV { get; set; }

    public virtual CALENDARIO CALENDARIO { get; set; }
    public virtual FORMULARIOS_DEC FORMULARIOS_DEC { get; set; }
    public virtual ICollection<FM_BASESLIQ01> FM_BASESLIQ01 { get; set; }
}

public partial class CALENDARIO
{
    public CALENDARIO()
    {
        this.ACPA_APG = new HashSet<ACPA_APG>();
        this.ACPA_DEUDA = new HashSet<ACPA_DEUDA>();
        this.BASES_LIQ = new HashSet<BASES_LIQ>();
        this.CARTERAD = new HashSet<CARTERAD>();
        this.DECLARACION = new HashSet<DECLARACION>();
        this.DOC_APG = new HashSet<DOC_APG>();
        this.EXPE_APG = new HashSet<EXPE_APG>();
        this.MOVIMIENTO = new HashSet<MOVIMIENTO>();
    }

    public string CAL_PER { get; set; }
    public string CAL_VIG { get; set; }
    public System.DateTime CAL_FINI { get; set; }
    public System.DateTime CAL_FFIN { get; set; }
    public string CAL_CLA { get; set; }
    public string CAL_DES { get; set; }
    public string CAL_USBD { get; set; }
    public string CAL_USAP { get; set; }
    public Nullable<System.DateTime> CAL_FREG { get; set; }
    public Nullable<System.DateTime> CAL_FNOV { get; set; }
    public Nullable<System.DateTime> CAL_FVEN { get; set; }

    public virtual ICollection<ACPA_APG> ACPA_APG { get; set; }
    public virtual ICollection<ACPA_DEUDA> ACPA_DEUDA { get; set; }
    public virtual ICollection<BASES_LIQ> BASES_LIQ { get; set; }
    public virtual CLASE_DEC CLASE_DEC { get; set; }
    public virtual ICollection<CARTERAD> CARTERAD { get; set; }
    public virtual ICollection<DECLARACION> DECLARACION { get; set; }
    public virtual ICollection<DOC_APG> DOC_APG { get; set; }
    public virtual ICollection<EXPE_APG> EXPE_APG { get; set; }
    public virtual ICollection<MOVIMIENTO> MOVIMIENTO { get; set; }
}

public partial class CARTERAD
{
    public string CAR_ID { get; set; }
    public string CAR_NIT { get; set; }
    public string CAR_ANO { get; set; }
    public string CAR_PER { get; set; }
    public string CAR_COCA { get; set; }
    public string CAR_TCON { get; set; }
    public long CAR_VADE { get; set; }
    public long CAR_VDB { get; set; }
    public long CAR_VCR { get; set; }
    public long CAR_VPA { get; set; }
    public string CAR_CDEC { get; set; }
    public string CAR_CCON { get; set; }
    public string CAR_CIMP { get; set; }
    public string CAR_TPAG { get; set; }
    public string CAR_VIG { get; set; }
    public System.DateTime CAR_FNOV { get; set; }
    public string CAR_EST { get; set; }
    public Nullable<System.DateTime> CAR_FREG { get; set; }
    public string CAR_USAP { get; set; }
    public string CAR_USBD { get; set; }
    public string CAR_DCOD { get; set; }
    public Nullable<System.DateTime> CAR_FVEN { get; set; }
    public string CAR_TDOC { get; set; }
    public string CAR_SUIM { get; set; }
    public string CAR_ACPA { get; set; }

    public virtual CALENDARIO CALENDARIO { get; set; }
    public virtual CONC_CART CONC_CART { get; set; }
    public virtual TIPO_CONCEPTOS TIPO_CONCEPTOS { get; set; }
    public virtual TIPO_DOC TIPO_DOC { get; set; }
}

public partial class CLASE_DEC
{
    public CLASE_DEC()
    {
        this.ACUE_PAGO = new HashSet<ACUE_PAGO>();
        this.CALENDARIO = new HashSet<CALENDARIO>();
        this.CLD_IMP = new HashSet<CLD_IMP>();
        this.CODE_CDEC = new HashSet<CODE_CDEC>();
        this.CONC_CDEC = new HashSet<CONC_CDEC>();
        this.DIST_CART = new HashSet<DIST_CART>();
        this.EXPEDIENTES = new HashSet<EXPEDIENTES>();
        this.FORMULARIOS_DEC = new HashSet<FORMULARIOS_DEC>();
        this.REQUI_DECLARACION = new HashSet<REQUI_DECLARACION>();
        this.TER_DEC = new HashSet<TER_DEC>();
        this.TIPO_DEC = new HashSet<TIPO_DEC>();
    }

    public string CLD_COD { get; set; }
    public string CLD_NOM { get; set; }
    public string CLD_USBD { get; set; }
    public string CLD_USAP { get; set; }
    public System.DateTime CLD_FREG { get; set; }
    public System.DateTime CLD_FNOV { get; set; }
    public System.DateTime CLD_FIN { get; set; }
    public System.DateTime CLD_FFI { get; set; }
    public string CLD_CONS { get; set; }
    public string CLD_EST { get; set; }

    public virtual ICollection<ACUE_PAGO> ACUE_PAGO { get; set; }
    public virtual ICollection<CALENDARIO> CALENDARIO { get; set; }
    public virtual ICollection<CLD_IMP> CLD_IMP { get; set; }
    public virtual ICollection<CODE_CDEC> CODE_CDEC { get; set; }
    public virtual ICollection<CONC_CDEC> CONC_CDEC { get; set; }
    public virtual ICollection<DIST_CART> DIST_CART { get; set; }
    public virtual ICollection<EXPEDIENTES> EXPEDIENTES { get; set; }
    public virtual ICollection<FORMULARIOS_DEC> FORMULARIOS_DEC { get; set; }
    public virtual ICollection<REQUI_DECLARACION> REQUI_DECLARACION { get; set; }
    public virtual ICollection<TER_DEC> TER_DEC { get; set; }
    public virtual ICollection<TIPO_DEC> TIPO_DEC { get; set; }
}

public partial class CLASE_IMPTO
{
    public string CLIM_CODI { get; set; }
    public string CLIM_NOMB { get; set; }
    public Nullable<System.DateTime> CLIM_FEIN { get; set; }
    public Nullable<System.DateTime> CLIM_FEFI { get; set; }
    public string CLIM_USBD { get; set; }
    public Nullable<System.DateTime> CLIM_FNOV { get; set; }
    public Nullable<System.DateTime> CLIM_FREG { get; set; }
    public string CLIM_USAP { get; set; }
}

public partial class CLASE_NOTIFICACION
{
    public string COD_NOTIFICACION { get; set; }
    public string DESCRIPCION { get; set; }
}

public partial class CLD_IMP
{
    public string CLD_COD { get; set; }
    public string CLD_CIMP { get; set; }
    public string CLD_ABIM { get; set; }
    public string CLD_ABVA { get; set; }
    public Nullable<System.DateTime> CLD_FNOV { get; set; }
    public Nullable<System.DateTime> CLD_FREG { get; set; }
    public string CLD_USAP { get; set; }
    public string CLD_USBD { get; set; }

    public virtual CLASE_DEC CLASE_DEC { get; set; }
    public virtual IMPUESTOS IMPUESTOS { get; set; }
}

public partial class CODE_CDEC
{
    public string CODE_CDEC1 { get; set; }
    public string CODE_CODI { get; set; }
    public string CODE_TICO { get; set; }
    public string CODE_NOMB { get; set; }
    public string CODE_TMOV { get; set; }
    public string CODE_ABVB { get; set; }
    public Nullable<decimal> CODE_VADE { get; set; }
    public string CODE_ABVD { get; set; }
    public Nullable<decimal> CODE_VACA { get; set; }
    public string CODE_SECO { get; set; }
    public Nullable<decimal> CODE_TARI { get; set; }
    public string CODE_IMPTO { get; set; }
    public string CODE_TSAN { get; set; }
    public string CODE_CART { get; set; }
    public Nullable<decimal> CODE_VABA { get; set; }
    public string CODE_ISVB { get; set; }
    public string CODE_REDE { get; set; }
    public string CODE_DENR { get; set; }
    public decimal CODE_VASU { get; set; }
    public Nullable<decimal> CODE_VAOF { get; set; }
    public string CODE_USBD { get; set; }
    public string CODE_USAP { get; set; }
    public string CODE_DEES { get; set; }
    public Nullable<System.DateTime> CODE_FREG { get; set; }
    public string CODE_PESA { get; set; }
    public string CODE_AÑSA { get; set; }
    public string CODE_CCAR { get; set; }
    public string CODE_SUM { get; set; }
    public string CODE_DCOD { get; set; }
    public string CODE_VIG { get; set; }
    public string CODE_DOAD { get; set; }
    public string CODE_CTAR { get; set; }
    public Nullable<System.DateTime> CODE_FNOV { get; set; }
    public Nullable<long> CODE_VBCA { get; set; }
    public Nullable<decimal> CODE_TACA { get; set; }

    public virtual CLASE_DEC CLASE_DEC { get; set; }
    public virtual DECLARACION DECLARACION { get; set; }
    public virtual SECCIONES SECCIONES { get; set; }
    public virtual TIPO_CONCEPTOS TIPO_CONCEPTOS { get; set; }
    public virtual TIPO_DOC TIPO_DOC { get; set; }
    public virtual VIGENCIA VIGENCIA { get; set; }
}

public partial class CON_ROF
{
    public string CORP_CDEC { get; set; }
    public string CORP_CODI { get; set; }
    public string CORP_TICO { get; set; }
    public string CORP_NOMB { get; set; }
    public string CORP_TMOV { get; set; }
    public string CORP_ABVB { get; set; }
    public Nullable<int> CORP_VADE { get; set; }
    public string CORP_ABVD { get; set; }
    public Nullable<int> CORP_VACA { get; set; }
    public string CORP_SECO { get; set; }
    public Nullable<decimal> CORP_TARI { get; set; }
    public string CORP_IMPTO { get; set; }
    public string CORP_TSAN { get; set; }
    public string CORP_CART { get; set; }
    public Nullable<int> CORP_VABA { get; set; }
    public string CORP_ISVB { get; set; }
    public string CORP_REDE { get; set; }
    public string CORP_DENR { get; set; }
    public int CORP_VASU { get; set; }
    public Nullable<int> CORP_VAOF { get; set; }
    public string CORP_USBD { get; set; }
    public string CORP_USAP { get; set; }
    public string CORP_DEES { get; set; }
    public Nullable<System.DateTime> CORP_FREG { get; set; }
    public string CORP_PESA { get; set; }
    public string CORP_AÑSA { get; set; }
    public string CORP_CCAR { get; set; }
    public string CORP_SUM { get; set; }
    public string CORP_DCOD { get; set; }
    public string CORP_VIG { get; set; }
    public string CORP_DOAD { get; set; }
    public string CORP_CTAR { get; set; }
    public Nullable<System.DateTime> CORP_FNOV { get; set; }
    public Nullable<long> CORP_VBCA { get; set; }
    public Nullable<decimal> CORP_TACA { get; set; }
}

public partial class CONC_CART
{
    public CONC_CART()
    {
        this.ACPA_DEUDA = new HashSet<ACPA_DEUDA>();
        this.CARTERAD = new HashSet<CARTERAD>();
        this.DIST_CART = new HashSet<DIST_CART>();
    }

    public string CCAR_COD { get; set; }
    public string CCAR_AVCO { get; set; }
    public string CCAR_NOM { get; set; }
    public string CCAR_TICO { get; set; }
    public string CCAR_CDEC { get; set; }
    public string CCAR_USAP { get; set; }
    public Nullable<System.DateTime> CCAR_FREG { get; set; }
    public Nullable<System.DateTime> CCAR_FNOV { get; set; }
    public string CCAR_USBD { get; set; }

    public virtual ICollection<ACPA_DEUDA> ACPA_DEUDA { get; set; }
    public virtual ICollection<CARTERAD> CARTERAD { get; set; }
    public virtual TIPO_CONCEPTOS TIPO_CONCEPTOS { get; set; }
    public virtual ICollection<DIST_CART> DIST_CART { get; set; }
}

public partial class CONC_CDEC
{
    public string COCD_CDEC { get; set; }
    public string COCD_CODI { get; set; }
    public string COCD_TICO { get; set; }
    public string COCD_NOMB { get; set; }
    public string COCD_REDE { get; set; }
    public string COCD_TMOV { get; set; }
    public string COCD_ABVB { get; set; }
    public Nullable<decimal> COCD_VADE { get; set; }
    public string COCD_ABVD { get; set; }
    public Nullable<int> COCD_VACA { get; set; }
    public string COCD_SECO { get; set; }
    public Nullable<decimal> COCD_TARI { get; set; }
    public string COCD_IMPTO { get; set; }
    public string COCD_TSAN { get; set; }
    public string COCD_CART { get; set; }
    public Nullable<int> COCD_VABA { get; set; }
    public string COCD_ISVB { get; set; }
    public string COCD_OPER { get; set; }
    public string COCD_CCAR { get; set; }
    public string COCD_AÑSA { get; set; }
    public string COCD_PESA { get; set; }
    public string COCD_SUM { get; set; }
    public string COCD_FDCO { get; set; }
    public string COCD_CTAR { get; set; }
    public Nullable<short> TIPO_TAR { get; set; }
    public string COCD_USAP { get; set; }
    public Nullable<System.DateTime> COCD_FREG { get; set; }
    public Nullable<System.DateTime> COCD_FNOV { get; set; }
    public string COCD_USBD { get; set; }
    public Nullable<int> COCD_REVB { get; set; }
    public string FORMULA { get; set; }

    public virtual CLASE_DEC CLASE_DEC { get; set; }
    public virtual FORMULARIOS_DEC FORMULARIOS_DEC { get; set; }
    public virtual SECCIONES SECCIONES { get; set; }
}

public partial class CONCEPTOS_IMP
{
    public string COIM_CIMP { get; set; }
    public string COIM_COD { get; set; }
    public string COIM_NOM { get; set; }
    public string COIM_TARIFA { get; set; }
    public Nullable<System.DateTime> COIM_FNOV { get; set; }
    public string COIM_EST { get; set; }
    public string COIM_PRI { get; set; }
    public string COIM_TCON { get; set; }
    public string COIM_TMOV { get; set; }
    public Nullable<decimal> COIM_IDX { get; set; }
    public string COIM_USBD { get; set; }
    public string COIM_USAP { get; set; }
    public Nullable<System.DateTime> COIM_FREG { get; set; }
}

public partial class CONSECUTIVOS
{
    public string CONS_VIG { get; set; }
    public int CONS_ID { get; set; }
    public string CONS_NOM { get; set; }
    public int CONS_PRX { get; set; }
    public int CONS_INI { get; set; }
    public string CONS_USAP { get; set; }
    public string CONS_USBD { get; set; }
    public Nullable<System.DateTime> CONS_FREG { get; set; }
    public Nullable<System.DateTime> CONS_FNOV { get; set; }

    public virtual VIGENCIA VIGENCIA { get; set; }
}

public partial class CONT_PERI
{
    public string COPE_AÑO { get; set; }
    public string COPE_MES { get; set; }
    public string COPE_ESTA { get; set; }
    public System.DateTime COPE_FNOV { get; set; }
    public string COPE_USBD { get; set; }
    public string COPE_USAP { get; set; }
    public Nullable<System.DateTime> COPE_FREG { get; set; }
}

public partial class COPIAS_RPT
{
    public string COP_COD { get; set; }
    public string COP_NOM { get; set; }
    public string COP_USAP { get; set; }
    public string COP_USBD { get; set; }
    public Nullable<System.DateTime> COP_FREG { get; set; }
    public Nullable<System.DateTime> COP_FNOV { get; set; }
}

public partial class CORREOSE
{
    public string CORR_CODI { get; set; }
    public string CORR_NOMB { get; set; }
    public string CORR_DATO { get; set; }
    public string CORR_BODY { get; set; }
    public string CORR_USAP { get; set; }
    public string CORR_USBD { get; set; }
    public Nullable<System.DateTime> CORR_FREG { get; set; }
    public Nullable<System.DateTime> CORR_FNOV { get; set; }
    public string CORR_CAMP { get; set; }
    public string CORR_VISTA { get; set; }
}

public partial class CTA_BANCO
{
    public CTA_BANCO()
    {
        this.PAGOS = new HashSet<PAGOS>();
    }

    public string CTA_BACO { get; set; }
    public string CTA_NRO { get; set; }
    public string CTA_TIP { get; set; }
    public string CTA_CODBAR { get; set; }
    public string CTA_EST { get; set; }
    public string CTA_USAP { get; set; }
    public string CTA_USBD { get; set; }
    public string CTA_DESC { get; set; }
    public string CTA_SUC { get; set; }
    public Nullable<System.DateTime> CTA_FREG { get; set; }
    public Nullable<System.DateTime> CTA_FNOV { get; set; }

    public virtual BANCOS BANCOS { get; set; }
    public virtual TIPO_CUENTA TIPO_CUENTA { get; set; }
    public virtual ICollection<PAGOS> PAGOS { get; set; }
}

public partial class CTRL_PAGOS
{
    public string NUM_LOTE { get; set; }
    public Nullable<System.DateTime> FECHA_SUBIDA { get; set; }
    public string OBSERVACION { get; set; }
    public Nullable<System.DateTime> FEC_REG { get; set; }
    public string USBD { get; set; }
    public Nullable<System.DateTime> FEC_MOD { get; set; }
    public string USAP { get; set; }
    public decimal ID { get; set; }
    public byte[] DOCUMENTO { get; set; }
}

public partial class CUOT_ACPA
{
    public string CUAP_APNU { get; set; }
    public int CUAP_CUNU { get; set; }
    public int CUAP_VALO { get; set; }
    public int CUAP_PAGO { get; set; }
    public System.DateTime CUAP_FEPA { get; set; }
    public System.DateTime CUAP_FREG { get; set; }
    public string CUAP_USBD { get; set; }
    public string CUAP_USAP { get; set; }
    public Nullable<System.DateTime> CUAP_FNOV { get; set; }

    public virtual ACUE_PAGO ACUE_PAGO { get; set; }
}

public partial class DEC_REQUI
{
    public string DR_CODDEC { get; set; }
    public string DR_PERI { get; set; }
    public string DR_ANO { get; set; }
    public string DR_CODREQ { get; set; }
    public string DR_ESTADO { get; set; }
    public System.DateTime DR_FECRAD { get; set; }
    public string DR_USBD { get; set; }
    public string DR_USAP { get; set; }
    public Nullable<System.DateTime> DR_FECPRE { get; set; }
    public string DR_FUNC { get; set; }
    public string DR_NRORAD { get; set; }
    public Nullable<System.DateTime> DR_FREG { get; set; }
    public Nullable<System.DateTime> DR_FNOV { get; set; }
    public string DR_CDEC { get; set; }

    public virtual REQUI_DECLARACION REQUI_DECLARACION { get; set; }
}

public partial class DECLARACION
{
    public DECLARACION()
    {
        this.CODE_CDEC = new HashSet<CODE_CDEC>();
    }

    public string DEC_NRO { get; set; }
    public string DEC_NIT { get; set; }
    public string DEC_PER { get; set; }
    public string DEC_ANO { get; set; }
    public string DEC_VIG { get; set; }
    public string DEC_EST { get; set; }
    public System.DateTime DEC_FREG { get; set; }
    public string DEC_CNRO { get; set; }
    public string DEC_USAP { get; set; }
    public string DEC_USBD { get; set; }
    public int DEC_CONS { get; set; }
    public string DEC_TIP { get; set; }
    public string DEC_SIG_DEC { get; set; }
    public string DEC_SIG_CTRF { get; set; }
    public string DEC_RAZSOC { get; set; }
    public string DEC_SCR_TIP { get; set; }
    public string DEC_SIG_DEC_TDOC { get; set; }
    public string DEC_SIG_CTRF_TDOC { get; set; }
    public string DEC_SIG_CTRF_NOM { get; set; }
    public string DEC_SIG_DEC_NOM { get; set; }
    public string DEC_SIG_CTRF_TAR_PRO { get; set; }
    public string DEC_TDOC { get; set; }
    public string DEC_DVER { get; set; }
    public Nullable<decimal> DEC_TRET { get; set; }
    public decimal DEC_TSAN { get; set; }
    public Nullable<decimal> DEC_TRS { get; set; }
    public Nullable<decimal> DEC_PRS { get; set; }
    public Nullable<decimal> DEC_PIM { get; set; }
    public Nullable<decimal> DEC_PTOT { get; set; }
    public string DEC_CSAN { get; set; }
    public string DEC_CDEC { get; set; }
    public string DEC_EST_FIS { get; set; }
    public Nullable<System.DateTime> DEC_FPRE { get; set; }
    public string DEC_COD { get; set; }
    public string DEC_FDCO { get; set; }
    public Nullable<System.DateTime> DEC_FVEN { get; set; }
    public string DEC_BACO { get; set; }
    public string DEC_CTA { get; set; }
    public string DEC_ROF { get; set; }
    public string DEC_DOAD { get; set; }
    public Nullable<System.DateTime> DEC_FNOV { get; set; }
    public string DEC_ESFI { get; set; }

    public virtual CALENDARIO CALENDARIO { get; set; }
    public virtual ICollection<CODE_CDEC> CODE_CDEC { get; set; }
    public virtual FORMULARIOS_DEC FORMULARIOS_DEC { get; set; }
    public virtual TERCEROS TERCEROS { get; set; }
    public virtual TERCEROS TERCEROS1 { get; set; }
    public virtual TERCEROS TERCEROS2 { get; set; }
    public virtual TIPO_DOC TIPO_DOC { get; set; }
    public virtual VIGENCIA VIGENCIA { get; set; }
}

public partial class DEPARTAMENTOS
{
    public string COD_DEPTO { get; set; }
    public string NOM_DEPTO { get; set; }
    public string ABREV_DISFON { get; set; }
    public string USAP { get; set; }
    public string USBD { get; set; }
    public Nullable<System.DateTime> FREG { get; set; }
    public Nullable<System.DateTime> FNOV { get; set; }
}

public partial class DIST_CART
{
    public string DICA_CDEC { get; set; }
    public string DICA_CODD { get; set; }
    public string DICA_CODC { get; set; }
    public string DICA_FDCO { get; set; }
    public Nullable<short> DICA_ORDE { get; set; }
    public string DICA_USAP { get; set; }
    public string DICA_USBD { get; set; }
    public Nullable<System.DateTime> DICA_FREG { get; set; }
    public Nullable<System.DateTime> DICA_FNOV { get; set; }

    public virtual CLASE_DEC CLASE_DEC { get; set; }
    public virtual CONC_CART CONC_CART { get; set; }
    public virtual FORMULARIOS_DEC FORMULARIOS_DEC { get; set; }
}

public partial class DOC_APG
{
    public string DAPG_NIT { get; set; }
    public string DAPG_CDEC { get; set; }
    public string DAPG_AÑO { get; set; }
    public string DAPG_PER { get; set; }
    public System.DateTime DAPG_FELA { get; set; }
    public Nullable<System.DateTime> DAPG_FNOT { get; set; }
    public string DAPG_ESTA { get; set; }
    public string DAPG_USBD { get; set; }
    public string DAPG_USAP { get; set; }
    public System.DateTime DAPG_FREG { get; set; }
    public string DAPG_DOAD { get; set; }
    public string DAPG_DCOD { get; set; }

    public virtual CALENDARIO CALENDARIO { get; set; }
    public virtual TIPO_DOC TIPO_DOC { get; set; }
}

public partial class DPAGO_ROAP
{
    public string DPAP_APNU { get; set; }
    public int DPAP_CUNU { get; set; }
    public int DPAP_PAGO { get; set; }
    public System.DateTime DPAP_FEPA { get; set; }
    public System.DateTime DPAP_FREG { get; set; }
    public string DPAP_USBD { get; set; }
    public string DPAP_USAP { get; set; }
    public Nullable<System.DateTime> DPAP_FNOV { get; set; }
    public string DPAP_RNUM { get; set; }
}

public partial class EMPRESA_MENSAJERIA
{
    public string COD_EMME { get; set; }
    public string DESCRIPCION { get; set; }
}

public partial class ENTIDAD
{
    public string ENT_NIT { get; set; }
    public string ENT_NOM { get; set; }
    public string ENT_DIR { get; set; }
    public string ENT_TEL { get; set; }
    public string ENT_EMAIL { get; set; }
    public string ENT_DPTO { get; set; }
    public string ENT_MPIO { get; set; }
    public string ENT_CEDRES { get; set; }
    public string ENT_NOMRES { get; set; }
    public string ENT_LOGO { get; set; }
    public string ENT_USAP { get; set; }
    public string ENT_USBD { get; set; }
    public Nullable<System.DateTime> ENT_FREG { get; set; }
    public Nullable<System.DateTime> ENT_FNOV { get; set; }
}

public partial class ESTADOS
{
    public ESTADOS()
    {
        this.VIGENCIA = new HashSet<VIGENCIA>();
    }

    public string EST_COD { get; set; }
    public string EST_DES { get; set; }
    public string EST_USAP { get; set; }
    public string EST_USBD { get; set; }
    public Nullable<System.DateTime> EST_FREG { get; set; }
    public Nullable<System.DateTime> EST_FNOV { get; set; }

    public virtual ICollection<VIGENCIA> VIGENCIA { get; set; }
}

public partial class EXPE_ANULA
{
    public string EXPE_NUME { get; set; }
    public string EXPE_ID { get; set; }
    public Nullable<System.DateTime> EXPE_FANU { get; set; }
    public string EXPE_OBSE { get; set; }
    public string TABLA { get; set; }
    public string EXPE_USAP { get; set; }
    public string EXPE_USBD { get; set; }
    public System.DateTime EXPE_FREG { get; set; }
}

public partial class EXPE_APG
{
    public string EXAP_NUME { get; set; }
    public string EXAP_DOAD { get; set; }
    public string EXAP_AGRA { get; set; }
    public string EXAP_PGRA { get; set; }
    public string EXAP_ESTA { get; set; }
    public string EXPE_USBD { get; set; }
    public string EXPE_USAP { get; set; }
    public System.DateTime EXPE_FREG { get; set; }
    public string EXAP_OBSE { get; set; }
    public string EXPE_CDEC { get; set; }
    public string EXAP_EXPR { get; set; }
    public string EXAP_SUIM { get; set; }
    public string EXAP_DCOD { get; set; }

    public virtual CALENDARIO CALENDARIO { get; set; }
    public virtual EXPEDIENTES EXPEDIENTES { get; set; }
    public virtual TIPO_DOC TIPO_DOC { get; set; }
}

public partial class EXPE_NOTIF
{
    public decimal EXNF_ID { get; set; }
    public Nullable<System.DateTime> EXNF_FREB { get; set; }
    public string EXNF_NOTIF { get; set; }
    public string EXNF_MEDIO { get; set; }
    public Nullable<System.DateTime> EXNF_FENV { get; set; }
    public string EXNF_REC { get; set; }
    public string EXNF_OBS { get; set; }
    public string EXNF_EMM { get; set; }
    public string EXTR_NUME { get; set; }
    public string EXTR_TRAC { get; set; }
    public string EXTR_GUIA { get; set; }
    public string EXTR_USAP { get; set; }
    public string EXTR_USBD { get; set; }
    public System.DateTime EXTR_FREG { get; set; }

    public virtual EXPEDIENTES EXPEDIENTES { get; set; }
}

public partial class EXPE_TRAM
{
    public string EXTR_NUME { get; set; }
    public string EXTR_DOAD { get; set; }
    public System.DateTime EXTR_FELA { get; set; }
    public string EXTR_TANT { get; set; }
    public string EXTR_TACT { get; set; }
    public string EXTR_TRNU { get; set; }
    public string EXTR_RENI { get; set; }
    public string EXTR_TRPT { get; set; }
    public string EXTR_RPTA { get; set; }
    public string EXTR_OBSE { get; set; }
    public string EXTR_ADJU { get; set; }
    public string EXTR_ANEX { get; set; }
    public string EXTR_USAP { get; set; }
    public string EXTR_USBD { get; set; }
    public System.DateTime EXTR_FREG { get; set; }
    public string EXTR_DONU { get; set; }
    public byte[] EXTR_PLAN { get; set; }
    public Nullable<System.DateTime> EXPE_FREB { get; set; }
    public Nullable<System.DateTime> EXPE_FEXP { get; set; }
    public string EXPE_NOTIF { get; set; }
    public byte[] EXTR_DOC { get; set; }
    public Nullable<decimal> EXTR_ID { get; set; }
    public string EXTR_DATO1 { get; set; }
    public byte[] EXTR_PDF { get; set; }

    public virtual EXPEDIENTES EXPEDIENTES { get; set; }
}

public partial class EXPEDIENTES
{
    public EXPEDIENTES()
    {
        this.EXPE_APG = new HashSet<EXPE_APG>();
        this.EXPE_NOTIF = new HashSet<EXPE_NOTIF>();
        this.EXPE_TRAM = new HashSet<EXPE_TRAM>();
    }

    public string EXPE_NIT { get; set; }
    public string EXPE_CDEC { get; set; }
    public System.DateTime EXPE_FELA { get; set; }
    public Nullable<System.DateTime> EXPE_FCIE { get; set; }
    public string EXPE_TRAC { get; set; }
    public string EXPE_USBD { get; set; }
    public string EXPE_USAP { get; set; }
    public System.DateTime EXPE_FREG { get; set; }
    public string EXPE_DOAD { get; set; }
    public string EXPE_DONU { get; set; }
    public System.DateTime EXPE_FNOV { get; set; }
    public string EXPE_OBSE { get; set; }
    public string EXPE_TPRO { get; set; }
    public string EXPE_PROC { get; set; }
    public string EXPE_ANEX { get; set; }
    public string EXPE_NUME { get; set; }
    public string EXPE_NPRO { get; set; }
    public Nullable<System.DateTime> EXPE_FEXP { get; set; }
    public Nullable<decimal> EXPE_EXTRID { get; set; }

    public virtual CLASE_DEC CLASE_DEC { get; set; }
    public virtual ICollection<EXPE_APG> EXPE_APG { get; set; }
    public virtual ICollection<EXPE_NOTIF> EXPE_NOTIF { get; set; }
    public virtual ICollection<EXPE_TRAM> EXPE_TRAM { get; set; }
    public virtual PROCESOS PROCESOS { get; set; }
    public virtual TIPO_DOC TIPO_DOC { get; set; }
    public virtual TIPO_PROCESO TIPO_PROCESO { get; set; }
    public virtual TRAMITES TRAMITES { get; set; }
}

public partial class FM_BASESLIQ01
{
    public long NIT_AR { get; set; }
    public short DV_AR { get; set; }
    public string CDEC { get; set; }
    public string IMPTO { get; set; }
    public string AGRAVABLE { get; set; }
    public string PGRAVABLE { get; set; }
    public long NDOC { get; set; }
    public System.DateTime FOPER { get; set; }
    public string TIDE { get; set; }
    public long NIDE { get; set; }
    public Nullable<short> DV { get; set; }
    public string RAZSOC { get; set; }
    public string CONCEPTO { get; set; }
    public decimal VALORBASE { get; set; }
    public decimal TARIFA { get; set; }
    public decimal VALORIMPTO { get; set; }
    public int NRO_RAD { get; set; }
    public string USAP { get; set; }
    public string USBD { get; set; }
    public System.DateTime FESI { get; set; }
    public Nullable<System.DateTime> FREG { get; set; }
    public Nullable<System.DateTime> FNOV { get; set; }
    public string COD_MPIO { get; set; }

    public virtual BASES_LIQ BASES_LIQ { get; set; }
}

public partial class FMTO_IMP
{
    public string FMIM_CAMP { get; set; }
    public string FMIM_TIDA { get; set; }
    public string FMIM_CODI { get; set; }
    public short FMIM_INDX { get; set; }
    public string FMIM_LONG { get; set; }
    public string FMIM_USAP { get; set; }
    public string FMIM_USBD { get; set; }
    public Nullable<System.DateTime> FMIM_FREG { get; set; }
    public Nullable<System.DateTime> FMIM_FNOV { get; set; }
    public string FMIM_EST { get; set; }

    public virtual TIPO_DATO TIPO_DATO { get; set; }
    public virtual FMTOS FMTOS { get; set; }
}

public partial class FMTOS
{
    public FMTOS()
    {
        this.FMTO_IMP = new HashSet<FMTO_IMP>();
    }

    public string FMTO_CODI { get; set; }
    public string FMTO_NOMB { get; set; }
    public string FMTO_DESC { get; set; }
    public string FMTO_CDEC { get; set; }
    public string FMTO_EST { get; set; }
    public string FMTO_USAP { get; set; }
    public string FMTO_USBD { get; set; }
    public Nullable<System.DateTime> FMTO_FREG { get; set; }
    public Nullable<System.DateTime> FMTO_FNOV { get; set; }

    public virtual ICollection<FMTO_IMP> FMTO_IMP { get; set; }
}

public partial class FORM_AYUD
{
    public string FOAY_CODI { get; set; }
    public Nullable<short> FOAY_NREN { get; set; }
    public string FOAY_FDCO { get; set; }
    public string FOAY_TITU { get; set; }
    public string FOAY_DESC { get; set; }
    public string FOAY_USAP { get; set; }
    public string FOAY_USBD { get; set; }
    public Nullable<System.DateTime> FOAY_FREG { get; set; }
    public Nullable<System.DateTime> FOAY_FNOV { get; set; }

    public virtual FORMULARIOS_DEC FORMULARIOS_DEC { get; set; }
}

public partial class FORMULARIOS_DEC
{
    public FORMULARIOS_DEC()
    {
        this.BASES_LIQ = new HashSet<BASES_LIQ>();
        this.CONC_CDEC = new HashSet<CONC_CDEC>();
        this.DECLARACION = new HashSet<DECLARACION>();
        this.DIST_CART = new HashSet<DIST_CART>();
        this.FORM_AYUD = new HashSet<FORM_AYUD>();
    }

    public string FODE_CODI { get; set; }
    public string FODE_CDEC { get; set; }
    public string FODE_FOWE { get; set; }
    public string FODE_RPTE { get; set; }
    public System.DateTime FODE_FEIN { get; set; }
    public System.DateTime FODE_FEFI { get; set; }
    public string FODE_USBD { get; set; }
    public System.DateTime FODE_FREG { get; set; }
    public string FODE_USAP { get; set; }
    public string FODE_OPER { get; set; }
    public string FODE_FOWI { get; set; }
    public string FODE_NOMB { get; set; }
    public string FODE_EST { get; set; }
    public string FODE_OPVP { get; set; }
    public Nullable<System.DateTime> FODE_FNOV { get; set; }
    public string FODE_OBS { get; set; }

    public virtual ICollection<BASES_LIQ> BASES_LIQ { get; set; }
    public virtual CLASE_DEC CLASE_DEC { get; set; }
    public virtual ICollection<CONC_CDEC> CONC_CDEC { get; set; }
    public virtual ICollection<DECLARACION> DECLARACION { get; set; }
    public virtual ICollection<DIST_CART> DIST_CART { get; set; }
    public virtual ICollection<FORM_AYUD> FORM_AYUD { get; set; }
}

public partial class FORMULASL
{
    public string FORM_CODI { get; set; }
    public System.DateTime FORM_FEIN { get; set; }
    public System.DateTime FORM_FEFI { get; set; }
    public string FORM_FORM { get; set; }
    public string FORM_NORM { get; set; }
    public string FORM_CONC { get; set; }
    public string FORM_USAP { get; set; }
    public string FORM_USBD { get; set; }
    public Nullable<System.DateTime> FORM_FREG { get; set; }
    public Nullable<System.DateTime> FORM_FNOV { get; set; }
}

public partial class FORMULASLT
{
    public string FORM_CODI { get; set; }
    public System.DateTime FORM_FEIN { get; set; }
    public System.DateTime FORM_FEFI { get; set; }
    public string FORM_FORM { get; set; }
    public string FORM_NORM { get; set; }
    public string FORM_CIMP { get; set; }
    public string FORM_USAP { get; set; }
    public string FORM_USBD { get; set; }
    public Nullable<System.DateTime> FORM_FREG { get; set; }
    public Nullable<System.DateTime> FORM_FNOV { get; set; }

    public virtual IMPUESTOS IMPUESTOS { get; set; }
}

public partial class HAUDITORIA
{
    public decimal HAUDCODI { get; set; }
    public string HAUDTABL { get; set; }
    public string HAUDIDEN { get; set; }
    public string HAUDTIPO { get; set; }
    public string HAUDDESC { get; set; }
    public string HAUDUSER { get; set; }
    public System.DateTime HAUDFESI { get; set; }
    public string HAUDUSBD { get; set; }
}

public partial class IMPUESTOS
{
    public IMPUESTOS()
    {
        this.CLD_IMP = new HashSet<CLD_IMP>();
        this.FORMULASLT = new HashSet<FORMULASLT>();
    }

    public string IMP_COD { get; set; }
    public string IMP_NOM { get; set; }
    public string IMP_OBS { get; set; }
    public string IMP_NOR { get; set; }
    public string IMP_CLA { get; set; }
    public string IMP_UNI { get; set; }
    public string IMP_USAP { get; set; }
    public string IMP_USBD { get; set; }
    public Nullable<System.DateTime> IMP_FREG { get; set; }
    public Nullable<System.DateTime> IMP_FNOV { get; set; }

    public virtual ICollection<CLD_IMP> CLD_IMP { get; set; }
    public virtual ICollection<FORMULASLT> FORMULASLT { get; set; }
    public virtual UNIDAD UNIDAD { get; set; }
}

public partial class MENU
{
    public MENU()
    {
        this.MENU1 = new HashSet<MENU>();
        this.MENU_PERFIL = new HashSet<MENU_PERFIL>();
    }

    public string MENUID { get; set; }
    public string TITULO { get; set; }
    public string DESCRIPCION { get; set; }
    public string PADREID { get; set; }
    public int POSICION { get; set; }
    public string ICONO { get; set; }
    public short HABILITADO { get; set; }
    public string URL { get; set; }
    public string MODULO { get; set; }
    public string ROLES { get; set; }
    public string TARGET { get; set; }
    public string PPAL { get; set; }
    public string USAP { get; set; }
    public string USBD { get; set; }
    public Nullable<System.DateTime> FREG { get; set; }
    public Nullable<System.DateTime> FNOV { get; set; }

    public virtual ICollection<MENU> MENU1 { get; set; }
    public virtual MENU MENU2 { get; set; }
    public virtual ICollection<MENU_PERFIL> MENU_PERFIL { get; set; }
}

public partial class MENU_PERFIL
{
    public string MENUID { get; set; }
    public string PERFIL { get; set; }
    public string MODULO { get; set; }
    public string USAP { get; set; }
    public string USBD { get; set; }
    public Nullable<System.DateTime> FREG { get; set; }
    public Nullable<System.DateTime> FNOV { get; set; }

    public virtual MENU MENU { get; set; }
}

public partial class MOVIMIENTO
{
    public decimal MOV_CONS { get; set; }
    public string MOV_NIT { get; set; }
    public string MOV_CDEC { get; set; }
    public string MOV_CCAR { get; set; }
    public string MOV_TICO { get; set; }
    public string MOV_AÑO { get; set; }
    public string MOV_PER { get; set; }
    public string MOV_CID { get; set; }
    public string MOV_SIG { get; set; }
    public Nullable<decimal> MOV_VDB { get; set; }
    public Nullable<decimal> MOV_VCR { get; set; }
    public Nullable<System.DateTime> MOV_FMOV { get; set; }
    public string MOV_EST { get; set; }
    public string MOV_USAP { get; set; }
    public string MOV_USBD { get; set; }
    public Nullable<System.DateTime> MOV_FNOV { get; set; }
    public string MOV_VIG { get; set; }
    public string MOV_TMOV { get; set; }
    public string MOV_TDOC { get; set; }
    public string MOV_NDOC { get; set; }
    public string MOV_PAG { get; set; }
    public Nullable<decimal> MOV_PAID { get; set; }
    public Nullable<System.DateTime> MOV_FREG { get; set; }

    public virtual CALENDARIO CALENDARIO { get; set; }
    public virtual TIPO_DOC TIPO_DOC { get; set; }
    public virtual TIPO_MOV TIPO_MOV { get; set; }
}

public partial class MUNICIPIOS
{
    public MUNICIPIOS()
    {
        this.TERCEROS = new HashSet<TERCEROS>();
    }

    public string MUN_COD { get; set; }
    public string MUN_NOM { get; set; }
    public string MUN_USAP { get; set; }
    public string MUN_USBD { get; set; }
    public Nullable<System.DateTime> MUN_FREG { get; set; }
    public Nullable<System.DateTime> MUN_FNOV { get; set; }
    public string MUN_DPCO { get; set; }

    public virtual ICollection<TERCEROS> TERCEROS { get; set; }
}

public partial class ORA_ASPNET_APPLICATIONS
{
    public ORA_ASPNET_APPLICATIONS()
    {
        this.ORA_ASPNET_ROLES = new HashSet<ORA_ASPNET_ROLES>();
        this.ORA_ASPNET_MEMBERSHIP = new HashSet<ORA_ASPNET_MEMBERSHIP>();
        this.ORA_ASPNET_PATHS = new HashSet<ORA_ASPNET_PATHS>();
        this.ORA_ASPNET_SITEMAP = new HashSet<ORA_ASPNET_SITEMAP>();
        this.ORA_ASPNET_USERS = new HashSet<ORA_ASPNET_USERS>();
    }

    public string APPLICATIONNAME { get; set; }
    public string LOWEREDAPPLICATIONNAME { get; set; }
    public System.Guid APPLICATIONID { get; set; }
    public string DESCRIPTION { get; set; }

    public virtual ICollection<ORA_ASPNET_ROLES> ORA_ASPNET_ROLES { get; set; }
    public virtual ICollection<ORA_ASPNET_MEMBERSHIP> ORA_ASPNET_MEMBERSHIP { get; set; }
    public virtual ICollection<ORA_ASPNET_PATHS> ORA_ASPNET_PATHS { get; set; }
    public virtual ICollection<ORA_ASPNET_SITEMAP> ORA_ASPNET_SITEMAP { get; set; }
    public virtual ICollection<ORA_ASPNET_USERS> ORA_ASPNET_USERS { get; set; }
}

public partial class ORA_ASPNET_MEMBERSHIP
{
    public System.Guid APPLICATIONID { get; set; }
    public System.Guid USERID { get; set; }
    public string PASSWORD { get; set; }
    public decimal PASSWORDFORMAT { get; set; }
    public string PASSWORDSALT { get; set; }
    public string MOBILEPIN { get; set; }
    public string EMAIL { get; set; }
    public string LOWEREDEMAIL { get; set; }
    public string PASSWORDQUESTION { get; set; }
    public string PASSWORDANSWER { get; set; }
    public decimal ISAPPROVED { get; set; }
    public decimal ISLOCKEDOUT { get; set; }
    public System.DateTime CREATEDATE { get; set; }
    public System.DateTime LASTLOGINDATE { get; set; }
    public System.DateTime LASTPASSWORDCHANGEDDATE { get; set; }
    public System.DateTime LASTLOCKOUTDATE { get; set; }
    public decimal FAILEDPWDATTEMPTCOUNT { get; set; }
    public System.DateTime FAILEDPWDATTEMPTWINSTART { get; set; }
    public decimal FAILEDPWDANSWERATTEMPTCOUNT { get; set; }
    public System.DateTime FAILEDPWDANSWERATTEMPTWINSTART { get; set; }
    public string COMMENTS { get; set; }

    public virtual ORA_ASPNET_APPLICATIONS ORA_ASPNET_APPLICATIONS { get; set; }
    public virtual ORA_ASPNET_USERS ORA_ASPNET_USERS { get; set; }
}

public partial class ORA_ASPNET_PATHS
{
    public ORA_ASPNET_PATHS()
    {
        this.ORA_ASPNET_PERSONALIZNALLUSERS = new HashSet<ORA_ASPNET_PERSONALIZNALLUSERS>();
        this.ORA_ASPNET_PERSONALIZNPERUSER = new HashSet<ORA_ASPNET_PERSONALIZNPERUSER>();
    }

    public System.Guid APPLICATIONID { get; set; }
    public System.Guid PATHID { get; set; }
    public string PATH { get; set; }
    public string LOWEREDPATH { get; set; }

    public virtual ORA_ASPNET_APPLICATIONS ORA_ASPNET_APPLICATIONS { get; set; }
    public virtual ICollection<ORA_ASPNET_PERSONALIZNALLUSERS> ORA_ASPNET_PERSONALIZNALLUSERS { get; set; }
    public virtual ICollection<ORA_ASPNET_PERSONALIZNPERUSER> ORA_ASPNET_PERSONALIZNPERUSER { get; set; }
}

public partial class ORA_ASPNET_PERSONALIZNALLUSERS
{
    public Nullable<System.Guid> PATHID { get; set; }
    public byte[] PAGESETTINGS { get; set; }
    public System.DateTime LASTUPDATEDDATE { get; set; }

    public virtual ORA_ASPNET_PATHS ORA_ASPNET_PATHS { get; set; }
}

public partial class ORA_ASPNET_PERSONALIZNPERUSER
{
    public System.Guid ID { get; set; }
    public Nullable<System.Guid> PATHID { get; set; }
    public Nullable<System.Guid> USERID { get; set; }
    public byte[] PAGESETTINGS { get; set; }
    public System.DateTime LASTUPDATEDDATE { get; set; }

    public virtual ORA_ASPNET_PATHS ORA_ASPNET_PATHS { get; set; }
    public virtual ORA_ASPNET_USERS ORA_ASPNET_USERS { get; set; }
}

public partial class ORA_ASPNET_PROFILE
{
    public System.Guid USERID { get; set; }
    public string PROPERTYNAMES { get; set; }
    public string PROPERTYVALUESSTRING { get; set; }
    public byte[] PROPERTYVALUESBINARY { get; set; }
    public System.DateTime LASTUPDATEDDATE { get; set; }

    public virtual ORA_ASPNET_USERS ORA_ASPNET_USERS { get; set; }
}

public partial class ORA_ASPNET_ROLES
{
    public ORA_ASPNET_ROLES()
    {
        this.ORA_ASPNET_USERS = new HashSet<ORA_ASPNET_USERS>();
    }

    public System.Guid APPLICATIONID { get; set; }
    public System.Guid ROLEID { get; set; }
    public string ROLENAME { get; set; }
    public string LOWEREDROLENAME { get; set; }
    public string DESCRIPTION { get; set; }

    public virtual ORA_ASPNET_APPLICATIONS ORA_ASPNET_APPLICATIONS { get; set; }
    public virtual ICollection<ORA_ASPNET_USERS> ORA_ASPNET_USERS { get; set; }
}

public partial class ORA_ASPNET_SESSIONAPPLICATIONS
{
    public System.Guid APPID { get; set; }
    public string APPNAME { get; set; }
}

public partial class ORA_ASPNET_SESSIONS
{
    public string SESSIONID { get; set; }
    public System.DateTime CREATED { get; set; }
    public System.DateTime EXPIRES { get; set; }
    public System.DateTime LOCKDATE { get; set; }
    public System.DateTime LOCKDATELOCAL { get; set; }
    public decimal LOCKCOOKIE { get; set; }
    public decimal TIMEOUT { get; set; }
    public decimal LOCKED { get; set; }
    public byte[] SESSIONITEMSHORT { get; set; }
    public byte[] SESSIONITEMLONG { get; set; }
    public decimal FLAGS { get; set; }
}

public partial class ORA_ASPNET_SITEMAP
{
    public Nullable<System.Guid> APPLICATIONID { get; set; }
    public int ID { get; set; }
    public string TITLE { get; set; }
    public string DESCRIPTION { get; set; }
    public string URL { get; set; }
    public string ROLES { get; set; }
    public Nullable<int> PARENT { get; set; }

    public virtual ORA_ASPNET_APPLICATIONS ORA_ASPNET_APPLICATIONS { get; set; }
}

public partial class ORA_ASPNET_USERS
{
    public ORA_ASPNET_USERS()
    {
        this.ORA_ASPNET_PERSONALIZNPERUSER = new HashSet<ORA_ASPNET_PERSONALIZNPERUSER>();
        this.ORA_ASPNET_ROLES = new HashSet<ORA_ASPNET_ROLES>();
    }

    public System.Guid APPLICATIONID { get; set; }
    public System.Guid USERID { get; set; }
    public string USERNAME { get; set; }
    public string LOWEREDUSERNAME { get; set; }
    public string MOBILEALIAS { get; set; }
    public decimal ISANONYMOUS { get; set; }
    public System.DateTime LASTACTIVITYDATE { get; set; }

    public virtual ORA_ASPNET_APPLICATIONS ORA_ASPNET_APPLICATIONS { get; set; }
    public virtual ORA_ASPNET_MEMBERSHIP ORA_ASPNET_MEMBERSHIP { get; set; }
    public virtual ICollection<ORA_ASPNET_PERSONALIZNPERUSER> ORA_ASPNET_PERSONALIZNPERUSER { get; set; }
    public virtual ORA_ASPNET_PROFILE ORA_ASPNET_PROFILE { get; set; }
    public virtual ICollection<ORA_ASPNET_ROLES> ORA_ASPNET_ROLES { get; set; }
}

public partial class PAGOS
{
    public string PAG_CDEC { get; set; }
    public string PAG_TDOC { get; set; }
    public string PAG_NDOC { get; set; }
    public string PAG_ANO { get; set; }
    public string PAG_PER { get; set; }
    public decimal PAG_TOT { get; set; }
    public System.DateTime PAG_FPAG { get; set; }
    public string PAG_EST { get; set; }
    public Nullable<decimal> PAG_SALD { get; set; }
    public string PAG_USAP { get; set; }
    public string PAG_USBD { get; set; }
    public System.DateTime PAG_FREG { get; set; }
    public string PAG_CTAB { get; set; }
    public string PAG_BACO { get; set; }
    public string PAG_NIT { get; set; }
    public int PAG_ID { get; set; }
    public Nullable<System.DateTime> PAG_FNOV { get; set; }

    public virtual CTA_BANCO CTA_BANCO { get; set; }
    public virtual TIPO_DOC TIPO_DOC { get; set; }
}

public partial class PAR_IMP
{
    public string PAR_CIM { get; set; }
    public string PAR_COD { get; set; }
    public string PAR_NOM { get; set; }
    public string PAR_TID { get; set; }
    public string PAR_TAM { get; set; }
    public string PAR_USAP { get; set; }
    public string PAR_USBD { get; set; }
    public Nullable<System.DateTime> PAR_FREG { get; set; }
    public Nullable<System.DateTime> PAR_FNOV { get; set; }
}

public partial class PAR_LIQ_DET
{
    public string PALI_PLCO { get; set; }
    public string PALI_COID { get; set; }
    public System.DateTime PALI_FEIN { get; set; }
    public System.DateTime PALI_FEFI { get; set; }
    public string PALI_VALO { get; set; }
    public string PAR_DEC { get; set; }
    public Nullable<decimal> PALI_VANU { get; set; }
    public Nullable<System.DateTime> PALI_VADA { get; set; }
    public string PALI_USAP { get; set; }
    public string PALI_USBD { get; set; }
    public Nullable<System.DateTime> PALI_FREG { get; set; }
    public Nullable<System.DateTime> PALI_FNOV { get; set; }

    public virtual PARA_LIQU PARA_LIQU { get; set; }
}

public partial class PARA_LIQU
{
    public PARA_LIQU()
    {
        this.PAR_LIQ_DET = new HashSet<PAR_LIQ_DET>();
    }

    public string PALI_CODI { get; set; }
    public string PALI_NOMB { get; set; }
    public string PALI_TIDA { get; set; }
    public string PALI_VARI { get; set; }
    public string PALI_ESTA { get; set; }
    public string PALI_DESC { get; set; }
    public string PALI_USAP { get; set; }
    public string PALI_USBD { get; set; }
    public Nullable<System.DateTime> PALI_FREG { get; set; }
    public Nullable<System.DateTime> PALI_FNOV { get; set; }

    public virtual ICollection<PAR_LIQ_DET> PAR_LIQ_DET { get; set; }
    public virtual TIPO_DATO TIPO_DATO { get; set; }
}

public partial class PROC_LOTE
{
    public string PRLT_NUM { get; set; }
    public byte[] PRLT_PLAN { get; set; }
    public byte[] PRLT_DOC { get; set; }
    public byte[] PRLT_PDF { get; set; }
    public string PRLT_TRAM { get; set; }
    public string PRLT_PROC { get; set; }
    public string PRLT_USAP { get; set; }
    public string PRLT_USBD { get; set; }
    public System.DateTime PRLT_FREG { get; set; }
    public string PRLT_CDEC { get; set; }
}

public partial class PROCESOS
{
    public PROCESOS()
    {
        this.EXPEDIENTES = new HashSet<EXPEDIENTES>();
    }

    public string PROC_CODI { get; set; }
    public string PROC_NOMB { get; set; }
    public string PROC_TPCO { get; set; }
    public string PROC_USAP { get; set; }
    public string PROC_USBD { get; set; }
    public System.DateTime PROC_FREG { get; set; }
    public System.DateTime PROC_FNOV { get; set; }
    public string PROC_HAB { get; set; }
    public string PROC_TINI { get; set; }
    public string PROC_TFIN { get; set; }

    public virtual ICollection<EXPEDIENTES> EXPEDIENTES { get; set; }
    public virtual TIPO_PROCESO TIPO_PROCESO { get; set; }
}

public partial class RECACUERDO
{
    public string RAP_CONS { get; set; }
    public string RAP_NIT { get; set; }
    public string RAP_PER { get; set; }
    public string RAP_ANO { get; set; }
    public string RAP_COD { get; set; }
    public string RAP_CDEC { get; set; }
    public string RAP_DECC { get; set; }
    public long RAP_VPA { get; set; }
    public string RAP_TRAP { get; set; }
    public Nullable<System.DateTime> RAP_FREG { get; set; }
    public string RAP_EST { get; set; }
    public string RAP_TDOC { get; set; }
    public Nullable<System.DateTime> RAP_FRAD { get; set; }
    public System.DateTime RAP_FNOV { get; set; }
    public string RAP_USBD { get; set; }
    public string RAP_USAP { get; set; }
}

public partial class RECOFICIAL
{
    public string ROF_CONS { get; set; }
    public string ROF_NIT { get; set; }
    public long ROF_VPA { get; set; }
    public decimal ROF_INT { get; set; }
    public string ROF_COD { get; set; }
    public string ROF_CDEC { get; set; }
    public string ROF_DECC { get; set; }
    public System.DateTime ROF_FNOV { get; set; }
    public string ROF_USBD { get; set; }
    public string ROF_USAP { get; set; }
    public Nullable<System.DateTime> ROF_FREG { get; set; }
    public string ROF_EST { get; set; }
    public Nullable<long> ROF_SAN { get; set; }
    public string ROF_TDOC { get; set; }
    public Nullable<System.DateTime> ROF_FRAD { get; set; }
    public string ROF_TROF { get; set; }
    public Nullable<int> ROF_TPAG { get; set; }
    public string ROF_CTABCO { get; set; }
    public string ROF_BCO { get; set; }
    public string ROF_ANO { get; set; }
    public string ROF_PER { get; set; }
}

public partial class REL_INT_MORA
{
    public string RLIM_NUM { get; set; }
    public string RLIM_DOAD { get; set; }
    public Nullable<decimal> RLIM_VALOR { get; set; }
    public string RLIM_TDOC { get; set; }
    public string RLIM_PER { get; set; }
    public string RLIM_ANO { get; set; }
    public string RLIM_NIT { get; set; }
    public string RLIM_DCOD { get; set; }
    public string RLIM_CDEC { get; set; }
    public string RLIM_USAP { get; set; }
    public string RLIM_USBD { get; set; }
    public System.DateTime RLIM_FREG { get; set; }
}

public partial class RELA_AGETER
{
    public Nullable<decimal> REL_CONS { get; set; }
    public string REL_TDOC { get; set; }
    public string REL_AGE { get; set; }
    public string REL_DVER { get; set; }
    public string REL_TDOCREV { get; set; }
    public string REL_REV { get; set; }
    public string REL_TREV { get; set; }
    public string REL_TARPRO { get; set; }
    public string REL_TDOCDEC { get; set; }
    public string REL_DEC { get; set; }
    public string REL_TDEC { get; set; }
    public string REL_EST { get; set; }
    public string REL_USBD { get; set; }
    public string REL_USAP { get; set; }
    public Nullable<System.DateTime> REL_FNOV { get; set; }
    public Nullable<System.DateTime> REL_FREG { get; set; }

    public virtual TERCEROS TERCEROS { get; set; }
    public virtual TERCEROS TERCEROS1 { get; set; }
}

public partial class REQUI_DECLARACION
{
    public REQUI_DECLARACION()
    {
        this.DEC_REQUI = new HashSet<DEC_REQUI>();
    }

    public string REQ_CLDEC { get; set; }
    public string REQ_COD { get; set; }
    public string REQ_DESC { get; set; }
    public System.DateTime REQ_FINI { get; set; }
    public Nullable<System.DateTime> REQ_FFIN { get; set; }
    public string REQ_USAP { get; set; }
    public string REQ_USBD { get; set; }
    public Nullable<System.DateTime> REQ_FREG { get; set; }
    public Nullable<System.DateTime> REQ_FNOV { get; set; }

    public virtual CLASE_DEC CLASE_DEC { get; set; }
    public virtual ICollection<DEC_REQUI> DEC_REQUI { get; set; }
}

public partial class SECCIONES
{
    public SECCIONES()
    {
        this.CODE_CDEC = new HashSet<CODE_CDEC>();
        this.CONC_CDEC = new HashSet<CONC_CDEC>();
    }

    public string SECC_CODI { get; set; }
    public string SECC_NOMB { get; set; }
    public string SECC_USAP { get; set; }
    public string SECC_USBD { get; set; }
    public Nullable<System.DateTime> SECC_FREG { get; set; }
    public Nullable<System.DateTime> SECC_FNOV { get; set; }

    public virtual ICollection<CODE_CDEC> CODE_CDEC { get; set; }
    public virtual ICollection<CONC_CDEC> CONC_CDEC { get; set; }
}

public partial class TARIFAS_IMP
{
    public System.DateTime TARI_FEIN { get; set; }
    public System.DateTime TARI_FEFI { get; set; }
    public string TARI_FORM { get; set; }
    public string TARI_NORM { get; set; }
    public string TARI_IMP { get; set; }
    public string TARI_CODI { get; set; }
    public string TARI_USAP { get; set; }
    public string TARI_USBD { get; set; }
    public Nullable<System.DateTime> TARI_FREG { get; set; }
    public Nullable<System.DateTime> TARI_FNOV { get; set; }
}

public partial class TDECLARANTE
{
    public string TDEC_COD { get; set; }
    public string TDEC_NOMB { get; set; }
    public string TDEC_USAP { get; set; }
    public string TDEC_USBD { get; set; }
    public Nullable<System.DateTime> TDEC_FREG { get; set; }
    public Nullable<System.DateTime> TDEC_FNOV { get; set; }
}

public partial class TDOC_IDE
{
    public TDOC_IDE()
    {
        this.TERCEROS = new HashSet<TERCEROS>();
    }

    public string TDOC_COD { get; set; }
    public string TDOC_NOM { get; set; }
    public string TDOC_USAP { get; set; }
    public string TDOC_USBD { get; set; }
    public Nullable<System.DateTime> TDOC_FREG { get; set; }
    public Nullable<System.DateTime> TDOC_FNOV { get; set; }

    public virtual ICollection<TERCEROS> TERCEROS { get; set; }
}

public partial class TER_DEC
{
    public string TEDE_CODI { get; set; }
    public string TEDE_TNIT { get; set; }
    public string TEDE_CDEC { get; set; }
    public Nullable<System.DateTime> TEDE_FINI { get; set; }
    public Nullable<System.DateTime> TEDE_FFIN { get; set; }
    public string TEDE_USAP { get; set; }
    public string TEDE_USBD { get; set; }
    public Nullable<System.DateTime> TEDE_FREG { get; set; }
    public Nullable<System.DateTime> TEDE_FNOV { get; set; }

    public virtual CLASE_DEC CLASE_DEC { get; set; }
}

public partial class TERCEROS
{
    public TERCEROS()
    {
        this.ACUE_PAGO = new HashSet<ACUE_PAGO>();
        this.DECLARACION = new HashSet<DECLARACION>();
        this.DECLARACION1 = new HashSet<DECLARACION>();
        this.DECLARACION2 = new HashSet<DECLARACION>();
        this.RELA_AGETER1 = new HashSet<RELA_AGETER>();
    }

    public int TER_CONS { get; set; }
    public string TER_TDOC { get; set; }
    public string TER_NIT { get; set; }
    public string TER_DVER { get; set; }
    public string TER_NOM { get; set; }
    public string TER_TIP { get; set; }
    public string TER_MPIO { get; set; }
    public string TER_EMAI { get; set; }
    public string TER_TEL { get; set; }
    public string TER_DIR { get; set; }
    public string TER_CED { get; set; }
    public string TER_REP { get; set; }
    public string TER_USU { get; set; }
    public string TER_TUS { get; set; }
    public System.DateTime TER_FREG { get; set; }
    public System.DateTime TER_FNOV { get; set; }
    public Nullable<System.DateTime> TER_FFIN { get; set; }
    public string TER_EST { get; set; }
    public string TER_OBS { get; set; }
    public string TER_USAP { get; set; }
    public string TER_USBD { get; set; }
    public string TER_REP_TD { get; set; }
    public string TER_REP_EXP { get; set; }

    public virtual ICollection<ACUE_PAGO> ACUE_PAGO { get; set; }
    public virtual ICollection<DECLARACION> DECLARACION { get; set; }
    public virtual ICollection<DECLARACION> DECLARACION1 { get; set; }
    public virtual ICollection<DECLARACION> DECLARACION2 { get; set; }
    public virtual MUNICIPIOS MUNICIPIOS { get; set; }
    public virtual RELA_AGETER RELA_AGETER { get; set; }
    public virtual ICollection<RELA_AGETER> RELA_AGETER1 { get; set; }
    public virtual TDOC_IDE TDOC_IDE { get; set; }
}

public partial class TIPO_AGENT
{
    public string TAG_COD { get; set; }
    public string TAG_NOM { get; set; }
    public string TAG_EST { get; set; }
    public string TAG_USAP { get; set; }
    public string TAG_USBD { get; set; }
    public Nullable<System.DateTime> TAG_FREG { get; set; }
    public Nullable<System.DateTime> TAG_FNOV { get; set; }
}

public partial class TIPO_CONCEPTOS
{
    public TIPO_CONCEPTOS()
    {
        this.CARTERAD = new HashSet<CARTERAD>();
        this.CODE_CDEC = new HashSet<CODE_CDEC>();
        this.CONC_CART = new HashSet<CONC_CART>();
    }

    public string TCON_COD { get; set; }
    public string TCON_NOM { get; set; }
    public string TCON_USAP { get; set; }
    public string TCON_USBD { get; set; }
    public System.DateTime TCON_FREG { get; set; }
    public System.DateTime TCON_FNOV { get; set; }

    public virtual ICollection<CARTERAD> CARTERAD { get; set; }
    public virtual ICollection<CODE_CDEC> CODE_CDEC { get; set; }
    public virtual ICollection<CONC_CART> CONC_CART { get; set; }
}

public partial class TIPO_CUENTA
{
    public TIPO_CUENTA()
    {
        this.CTA_BANCO = new HashSet<CTA_BANCO>();
    }

    public string TCTA_CODI { get; set; }
    public string TCTA_NOMB { get; set; }
    public string TCTA_USAP { get; set; }
    public string TCTA_USBD { get; set; }
    public Nullable<System.DateTime> TCTA_FREG { get; set; }
    public Nullable<System.DateTime> TCTA_FNOV { get; set; }

    public virtual ICollection<CTA_BANCO> CTA_BANCO { get; set; }
}

public partial class TIPO_DATO
{
    public TIPO_DATO()
    {
        this.FMTO_IMP = new HashSet<FMTO_IMP>();
        this.PARA_LIQU = new HashSet<PARA_LIQU>();
    }

    public string TIDA_CODI { get; set; }
    public string TIDA_ORACLE { get; set; }
    public string TIDA_NET { get; set; }
    public string TIDA_USAP { get; set; }
    public string TIDA_USBD { get; set; }
    public System.DateTime TIDA_FREG { get; set; }
    public System.DateTime TIDA_FNOV { get; set; }

    public virtual ICollection<FMTO_IMP> FMTO_IMP { get; set; }
    public virtual ICollection<PARA_LIQU> PARA_LIQU { get; set; }
}

public partial class TIPO_DEC
{
    public string TDEC_COD { get; set; }
    public string TDEC_NOM { get; set; }
    public Nullable<System.DateTime> TDEC_FIN { get; set; }
    public Nullable<System.DateTime> TDEC_FFI { get; set; }
    public string TDEC_USBD { get; set; }
    public string TDEC_USAP { get; set; }
    public System.DateTime TDEC_FREG { get; set; }
    public System.DateTime TDEC_FNOV { get; set; }
    public string TDEC_CDEC { get; set; }
    public string TDEC_CODI { get; set; }

    public virtual CLASE_DEC CLASE_DEC { get; set; }
}

public partial class TIPO_DOC
{
    public TIPO_DOC()
    {
        this.ACPA_DEUDA = new HashSet<ACPA_DEUDA>();
        this.CARTERAD = new HashSet<CARTERAD>();
        this.CODE_CDEC = new HashSet<CODE_CDEC>();
        this.DECLARACION = new HashSet<DECLARACION>();
        this.DOC_APG = new HashSet<DOC_APG>();
        this.EXPE_APG = new HashSet<EXPE_APG>();
        this.EXPEDIENTES = new HashSet<EXPEDIENTES>();
        this.TIPO_DOC_CONS = new HashSet<TIPO_DOC_CONS>();
        this.MOVIMIENTO = new HashSet<MOVIMIENTO>();
        this.PAGOS = new HashSet<PAGOS>();
    }

    public string TIDO_CODI { get; set; }
    public string TIDO_NOMB { get; set; }
    public string TIDO_EST { get; set; }
    public string TIDO_USAP { get; set; }
    public string TIDO_USBD { get; set; }
    public Nullable<System.DateTime> TIDO_FREG { get; set; }
    public Nullable<System.DateTime> TIDO_FNOV { get; set; }
    public byte[] TIDO_FIRMA { get; set; }
    public string TIDO_RESP { get; set; }

    public virtual ICollection<ACPA_DEUDA> ACPA_DEUDA { get; set; }
    public virtual ICollection<CARTERAD> CARTERAD { get; set; }
    public virtual ICollection<CODE_CDEC> CODE_CDEC { get; set; }
    public virtual ICollection<DECLARACION> DECLARACION { get; set; }
    public virtual ICollection<DOC_APG> DOC_APG { get; set; }
    public virtual ICollection<EXPE_APG> EXPE_APG { get; set; }
    public virtual ICollection<EXPEDIENTES> EXPEDIENTES { get; set; }
    public virtual ICollection<TIPO_DOC_CONS> TIPO_DOC_CONS { get; set; }
    public virtual ICollection<MOVIMIENTO> MOVIMIENTO { get; set; }
    public virtual ICollection<PAGOS> PAGOS { get; set; }
}

public partial class TIPO_DOC_CONS
{
    public string TIDO_CODI { get; set; }
    public string TIDO_CDEC { get; set; }
    public string TIDO_CONS { get; set; }
    public string TIDO_USAP { get; set; }
    public string TIDO_USBD { get; set; }
    public Nullable<System.DateTime> TIDO_FREG { get; set; }
    public Nullable<System.DateTime> TIDO_FNOV { get; set; }

    public virtual TIPO_DOC TIPO_DOC { get; set; }
}

public partial class TIPO_MOV
{
    public TIPO_MOV()
    {
        this.MOVIMIENTO = new HashSet<MOVIMIENTO>();
    }

    public string TMOV_COD { get; set; }
    public string TMOV_NOM { get; set; }
    public string TMOV_USAP { get; set; }
    public string TMOV_USBD { get; set; }
    public Nullable<System.DateTime> TMOV_FREG { get; set; }
    public Nullable<System.DateTime> TMOV_FNOV { get; set; }

    public virtual ICollection<MOVIMIENTO> MOVIMIENTO { get; set; }
}

public partial class TIPO_PAGO
{
    public string TPAG_COD { get; set; }
    public string TPAG_NOM { get; set; }
    public string TPAG_USAP { get; set; }
    public string TPAG_USBD { get; set; }
    public Nullable<System.DateTime> TPAG_FREG { get; set; }
    public Nullable<System.DateTime> TPAG_FNOV { get; set; }
}

public partial class TIPO_PROCESO
{
    public TIPO_PROCESO()
    {
        this.EXPEDIENTES = new HashSet<EXPEDIENTES>();
        this.PROCESOS = new HashSet<PROCESOS>();
    }

    public string TPRO_CODI { get; set; }
    public string TPRO_NOMB { get; set; }
    public string TPRO_USAP { get; set; }
    public string TPRO_USBD { get; set; }
    public Nullable<System.DateTime> TPRO_FREG { get; set; }
    public Nullable<System.DateTime> TPRO_FNOV { get; set; }

    public virtual ICollection<EXPEDIENTES> EXPEDIENTES { get; set; }
    public virtual ICollection<PROCESOS> PROCESOS { get; set; }
}

public partial class TIPO_SANCIONES
{
    public string TSAN_COD { get; set; }
    public string TSAN_NOM { get; set; }
    public string TSAN_FORM { get; set; }
    public string TSAN_PAR { get; set; }
    public string TSAN_DEC { get; set; }
    public string TSAN_DETI { get; set; }
    public string TSAN_USAP { get; set; }
    public string TSAN_USBD { get; set; }
    public Nullable<System.DateTime> TSAN_FREG { get; set; }
    public Nullable<System.DateTime> TSAN_FNOV { get; set; }
}

public partial class TIPOUSUA
{
    public string TUS_COD { get; set; }
    public string TUS_NOM { get; set; }
    public string TUS_USAP { get; set; }
    public string TUS_USBD { get; set; }
    public Nullable<System.DateTime> TUS_FREG { get; set; }
    public Nullable<System.DateTime> TUS_FNOV { get; set; }
}

public partial class TRAM_TER
{
    public string TRTE_NIT { get; set; }
    public string TRTE_TRAM { get; set; }
    public string TRTE_USAP { get; set; }
    public string TRTE_USBD { get; set; }
    public Nullable<System.DateTime> TRTE_FREG { get; set; }
    public Nullable<System.DateTime> TRTE_FNOV { get; set; }
}

public partial class TRAMITES
{
    public TRAMITES()
    {
        this.EXPEDIENTES = new HashSet<EXPEDIENTES>();
    }

    public string TRAM_CODI { get; set; }
    public string TRAM_NOMB { get; set; }
    public string TRAM_RESP { get; set; }
    public string TRAM_GSAN { get; set; }
    public string TRAM_COSA { get; set; }
    public string TRAM_PLAN { get; set; }
    public string TRAM_USAP { get; set; }
    public string TRAM_USBD { get; set; }
    public Nullable<System.DateTime> TRAM_FREG { get; set; }
    public Nullable<System.DateTime> TRAM_FNOV { get; set; }
    public string TRAM_PROC { get; set; }
    public string TRAM_TIDO { get; set; }
    public string TRAM_AUTO { get; set; }
    public Nullable<short> TRAM_DIAS { get; set; }
    public string TRAM_TIPO { get; set; }
    public string TRAM_VFREB { get; set; }
    public string TRAM_TPRO { get; set; }

    public virtual ICollection<EXPEDIENTES> EXPEDIENTES { get; set; }
}

public partial class TRAMRELA
{
    public string TRRE_DESD { get; set; }
    public string TRRE_PARA { get; set; }
    public short TRRE_DILI { get; set; }
    public string TRRE_USAP { get; set; }
    public string TRRE_USBD { get; set; }
    public Nullable<System.DateTime> TRRE_FREG { get; set; }
    public Nullable<System.DateTime> TRRE_FNOV { get; set; }
}

public partial class UNIDAD
{
    public UNIDAD()
    {
        this.IMPUESTOS = new HashSet<IMPUESTOS>();
    }

    public string UNI_COD { get; set; }
    public string UNI_NOM { get; set; }
    public string UNI_USAP { get; set; }
    public string UNI_USBD { get; set; }
    public Nullable<System.DateTime> UNI_FREG { get; set; }
    public Nullable<System.DateTime> UNI_FNOV { get; set; }

    public virtual ICollection<IMPUESTOS> IMPUESTOS { get; set; }
}

public partial class USEREXT
{
    public string USERNAME { get; set; }
    public string TIPO_USUARIO { get; set; }
    public string PERFIL { get; set; }
    public string USAP { get; set; }
    public string USBD { get; set; }
    public Nullable<System.DateTime> FREG { get; set; }
    public Nullable<System.DateTime> FNOV { get; set; }
}

public partial class VH_ASEGURADORA
{
    public string COD_ASEG { get; set; }
    public string NOM_ASEG { get; set; }
    public string EST_ASEG { get; set; }
}

public partial class VH_BG_AUTO_2007
{
    public int GRUPO { get; set; }
    public string MARCA { get; set; }
    public string LINEA { get; set; }
    public Nullable<int> CILINDRADA { get; set; }
    public Nullable<decimal> V1983 { get; set; }
    public Nullable<decimal> V1984 { get; set; }
    public Nullable<decimal> V1985 { get; set; }
    public Nullable<decimal> V1986 { get; set; }
    public Nullable<decimal> V1987 { get; set; }
    public Nullable<decimal> V1988 { get; set; }
    public Nullable<decimal> V1989 { get; set; }
    public Nullable<decimal> V1990 { get; set; }
    public Nullable<decimal> V1991 { get; set; }
    public Nullable<decimal> V1992 { get; set; }
    public Nullable<decimal> V1993 { get; set; }
    public Nullable<decimal> V1994 { get; set; }
    public Nullable<decimal> V1995 { get; set; }
    public Nullable<decimal> V1996 { get; set; }
    public Nullable<decimal> V1997 { get; set; }
    public Nullable<decimal> V1998 { get; set; }
    public Nullable<decimal> V1999 { get; set; }
    public Nullable<decimal> V2000 { get; set; }
    public Nullable<decimal> V2001 { get; set; }
    public Nullable<decimal> V2002 { get; set; }
    public Nullable<decimal> V2003 { get; set; }
    public Nullable<decimal> V2004 { get; set; }
    public Nullable<decimal> V2005 { get; set; }
    public Nullable<decimal> V2006 { get; set; }
    public string LINEA_H { get; set; }
}

public partial class VH_BG_AUTO_2008
{
    public int GRUPO { get; set; }
    public string MARCA { get; set; }
    public string LINEA { get; set; }
    public string LINEA_H { get; set; }
    public Nullable<int> CILINDRADA { get; set; }
    public Nullable<decimal> V1983 { get; set; }
    public Nullable<decimal> V1984 { get; set; }
    public Nullable<decimal> V1985 { get; set; }
    public Nullable<decimal> V1986 { get; set; }
    public Nullable<decimal> V1987 { get; set; }
    public Nullable<decimal> V1988 { get; set; }
    public Nullable<decimal> V1989 { get; set; }
    public Nullable<decimal> V1990 { get; set; }
    public Nullable<decimal> V1991 { get; set; }
    public Nullable<decimal> V1992 { get; set; }
    public Nullable<decimal> V1993 { get; set; }
    public Nullable<decimal> V1994 { get; set; }
    public Nullable<decimal> V1995 { get; set; }
    public Nullable<decimal> V1996 { get; set; }
    public Nullable<decimal> V1997 { get; set; }
    public Nullable<decimal> V1998 { get; set; }
    public Nullable<decimal> V1999 { get; set; }
    public Nullable<decimal> V2000 { get; set; }
    public Nullable<decimal> V2001 { get; set; }
    public Nullable<decimal> V2002 { get; set; }
    public Nullable<decimal> V2003 { get; set; }
    public Nullable<decimal> V2004 { get; set; }
    public Nullable<decimal> V2005 { get; set; }
    public Nullable<decimal> V2006 { get; set; }
    public Nullable<decimal> V2007 { get; set; }
}

public partial class VH_BG_AUTO_2009
{
    public int GRUPO { get; set; }
    public string MARCA { get; set; }
    public string LINEA { get; set; }
    public string LINEA_H { get; set; }
    public Nullable<int> CILINDRADA { get; set; }
    public Nullable<decimal> V1984 { get; set; }
    public Nullable<decimal> V1985 { get; set; }
    public Nullable<decimal> V1986 { get; set; }
    public Nullable<decimal> V1987 { get; set; }
    public Nullable<decimal> V1988 { get; set; }
    public Nullable<decimal> V1989 { get; set; }
    public Nullable<decimal> V1990 { get; set; }
    public Nullable<decimal> V1991 { get; set; }
    public Nullable<decimal> V1992 { get; set; }
    public Nullable<decimal> V1993 { get; set; }
    public Nullable<decimal> V1994 { get; set; }
    public Nullable<decimal> V1995 { get; set; }
    public Nullable<decimal> V1996 { get; set; }
    public Nullable<decimal> V1997 { get; set; }
    public Nullable<decimal> V1998 { get; set; }
    public Nullable<decimal> V1999 { get; set; }
    public Nullable<decimal> V2000 { get; set; }
    public Nullable<decimal> V2001 { get; set; }
    public Nullable<decimal> V2002 { get; set; }
    public Nullable<decimal> V2003 { get; set; }
    public Nullable<decimal> V2004 { get; set; }
    public Nullable<decimal> V2005 { get; set; }
    public Nullable<decimal> V2006 { get; set; }
    public Nullable<decimal> V2007 { get; set; }
    public Nullable<decimal> V2008 { get; set; }
}

public partial class VH_CAPACIDAD_M
{
    public string GRUPO { get; set; }
    public Nullable<int> DESDE { get; set; }
    public Nullable<int> HASTA { get; set; }
    public string VIG { get; set; }
    public string DESCRIPCION { get; set; }
}

public partial class VH_CARGA_LETRA
{
    public string TIPO { get; set; }
    public string GRUPO { get; set; }
    public string MARCA { get; set; }
    public string VIG { get; set; }
    public string CLASE_Y_CARROCERIA { get; set; }
    public string CLASIFICACION { get; set; }
    public string MARCA_H { get; set; }
}

public partial class VH_CARROCERIA
{
    public string NOM_CARROCERIA { get; set; }
    public Nullable<decimal> ID_VH_CARROCERIA { get; set; }
}

public partial class VH_CATEGORIA
{
    public string VCAT_CATEGORIA { get; set; }
    public Nullable<decimal> VCAT_ID { get; set; }
}

public partial class VH_CLASE_CATEGORIA
{
    public string VCC_CLASE { get; set; }
    public string VCC_CATEGORIA { get; set; }
    public string VCC_VIGENCIA { get; set; }
}

public partial class VH_CLASE_LIQ
{
    public string VCL_CLASE { get; set; }
    public string VCL_CODIGO { get; set; }
}

public partial class VH_COLOR
{
    public string NOM_COLOR { get; set; }
    public Nullable<decimal> ID_VH_COLOR { get; set; }
}

public partial class VH_DATOS_LIQ
{
    public string DECCOD { get; set; }
    public string PLACA { get; set; }
    public string CLASE { get; set; }
    public string MARCA { get; set; }
    public string LINEA { get; set; }
    public string MODELO { get; set; }
    public string COLOR { get; set; }
    public string CARROCERIA { get; set; }
    public Nullable<int> CILINDRAJE { get; set; }
    public Nullable<int> TONELAJE { get; set; }
    public Nullable<int> PASAJEROS { get; set; }
    public string MOTOR { get; set; }
    public string CHASIS { get; set; }
    public string BLINDADO { get; set; }
    public string ANTIGUO { get; set; }
    public string NIT { get; set; }
    public Nullable<System.DateTime> FECHA_COMPRA { get; set; }
    public string MUN_MATRICULA { get; set; }
    public string MUN_OPERACION { get; set; }
    public Nullable<System.DateTime> FECHA_MAT { get; set; }
    public string TIPO_MATRICULA { get; set; }
    public string COD_ASEGURADORA { get; set; }
    public string N_POLIZA { get; set; }
    public Nullable<System.DateTime> FECHA_VENCIMIENTO { get; set; }
    public Nullable<decimal> CONS { get; set; }
    public Nullable<System.DateTime> FEC_LIQ { get; set; }
    public string ESTADO { get; set; }
    public Nullable<decimal> AVALUO { get; set; }
    public Nullable<decimal> TARIFA { get; set; }
    public string DSC_MAT_TRA { get; set; }
    public Nullable<short> FRACCION { get; set; }
    public Nullable<decimal> DEC_STOT { get; set; }
    public string NOM_ASEGURADORA { get; set; }
    public Nullable<int> NRO_LIQG { get; set; }
}

public partial class VH_INSTITUTO_TRANSITO
{
    public string VINS_CODIGO { get; set; }
    public string VINS_DESCRIPCION { get; set; }
}

public partial class VH_LINEA
{
    public string NOM_LINEA { get; set; }
    public Nullable<decimal> ID_VH_LINEA { get; set; }
    public Nullable<decimal> ID_VH_MARCA { get; set; }
}

public partial class VH_LIQ_GRUPAL
{
    public int NRO_LIQG { get; set; }
    public Nullable<System.DateTime> FECHA_INI { get; set; }
    public Nullable<System.DateTime> FECHA_FIN { get; set; }
    public string USBD { get; set; }
    public string USAP { get; set; }
    public string ESTADO { get; set; }
    public Nullable<decimal> TOTAL { get; set; }
}

public partial class VH_LIQUIDLOG
{
    public int NRO_LIQG { get; set; }
    public string PLACA { get; set; }
    public string OBSERVACION { get; set; }
    public string LIQUIDO { get; set; }
    public string CATEGORIA_LIQ { get; set; }
    public Nullable<System.DateTime> FECHA_REG { get; set; }
    public string USBD { get; set; }
    public string USAP { get; set; }
    public string VIGENCIALIQ { get; set; }
    public string FILTROVEH { get; set; }
    public string DEC_COD { get; set; }
    public Nullable<int> LIQ_CONS { get; set; }
}

public partial class VH_MARCA_M
{
    public string GRUPO { get; set; }
    public string MARCA { get; set; }
    public string VIG { get; set; }
    public string MARCA_H { get; set; }
}

public partial class VH_PARQUE_AUTOMOTOR
{
    public string PLACA { get; set; }
    public string CLASE { get; set; }
    public string MARCA { get; set; }
    public string LINEA { get; set; }
    public string MODELO { get; set; }
    public string COLOR { get; set; }
    public string CARROCERIA { get; set; }
    public Nullable<int> CILINDRAJE { get; set; }
    public Nullable<int> TONELAJE { get; set; }
    public Nullable<int> PASAJEROS { get; set; }
    public string MOTOR { get; set; }
    public string CHASIS { get; set; }
    public string BLINDADO { get; set; }
    public string ANTIGUO { get; set; }
    public string NIT { get; set; }
    public Nullable<System.DateTime> FECHA_COMPRA { get; set; }
    public string MUN_MATRICULA { get; set; }
    public string MUN_OPERACION { get; set; }
    public Nullable<System.DateTime> FECHA_MAT { get; set; }
    public string TIPO_MATRICULA { get; set; }
    public Nullable<decimal> VALOR_FACT { get; set; }
    public string ESTADO { get; set; }
    public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
    public string PARQ_USAP { get; set; }
    public string PARQ_USBD { get; set; }
    public Nullable<System.DateTime> PARQ_FREG { get; set; }
    public Nullable<System.DateTime> FEC_EXP_TP { get; set; }
    public string VINS_CODIGO { get; set; }
    public string IMPORTADO { get; set; }
    public string USO { get; set; }
    public string CATEGORIA { get; set; }
}

public partial class VH_PASAJERO_CAP
{
    public string GRUPO { get; set; }
    public Nullable<int> DESDE { get; set; }
    public Nullable<int> HASTA { get; set; }
    public string VIG { get; set; }
    public string DESCRIPCION { get; set; }
}

public partial class VIGENCIA
{
    public VIGENCIA()
    {
        this.CODE_CDEC = new HashSet<CODE_CDEC>();
        this.CONSECUTIVOS = new HashSet<CONSECUTIVOS>();
        this.DECLARACION = new HashSet<DECLARACION>();
    }

    public string VIG_COD { get; set; }
    public System.DateTime VIG_FINI { get; set; }
    public Nullable<System.DateTime> VIG_FFIN { get; set; }
    public string VIG_EST { get; set; }
    public string VIG_USAP { get; set; }
    public string VIG_USBD { get; set; }
    public Nullable<System.DateTime> VIG_FREG { get; set; }
    public Nullable<System.DateTime> VIG_FNOV { get; set; }

    public virtual ICollection<CODE_CDEC> CODE_CDEC { get; set; }
    public virtual ICollection<CONSECUTIVOS> CONSECUTIVOS { get; set; }
    public virtual ICollection<DECLARACION> DECLARACION { get; set; }
    public virtual ESTADOS ESTADOS { get; set; }
}

