//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class MUNICIPIOS
    {
        public MUNICIPIOS()
        {
            this.TERCEROS = new HashSet<TERCEROS>();
        }
    
        public string MUN_COD { get; set; }
        public string MUN_NOM { get; set; }
        public string MUN_USAP { get; set; }
        public string MUN_USBD { get; set; }
        public Nullable<System.DateTime> MUN_FREG { get; set; }
        public Nullable<System.DateTime> MUN_FNOV { get; set; }
        public string MUN_DPCO { get; set; }
    
        public virtual ICollection<TERCEROS> TERCEROS { get; set; }
    }
    
}
