//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class ORA_ASPNET_SESSIONAPPLICATIONS
    {
        public System.Guid APPID { get; set; }
        public string APPNAME { get; set; }
    }
    
}
