//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class PAR_IMP
    {
        public string PAR_CIM { get; set; }
        public string PAR_COD { get; set; }
        public string PAR_NOM { get; set; }
        public string PAR_TID { get; set; }
        public string PAR_TAM { get; set; }
        public string PAR_USAP { get; set; }
        public string PAR_USBD { get; set; }
        public Nullable<System.DateTime> PAR_FREG { get; set; }
        public Nullable<System.DateTime> PAR_FNOV { get; set; }
    }
    
}
