//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class PROC_LOTE
    {
        public string PRLT_NUM { get; set; }
        public byte[] PRLT_PLAN { get; set; }
        public byte[] PRLT_DOC { get; set; }
        public byte[] PRLT_PDF { get; set; }
        public string PRLT_TRAM { get; set; }
        public string PRLT_PROC { get; set; }
        public string PRLT_USAP { get; set; }
        public string PRLT_USBD { get; set; }
        public System.DateTime PRLT_FREG { get; set; }
        public string PRLT_CDEC { get; set; }
    }
    
}
