//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class RECACUERDO
    {
        public string RAP_CONS { get; set; }
        public string RAP_NIT { get; set; }
        public string RAP_PER { get; set; }
        public string RAP_ANO { get; set; }
        public string RAP_COD { get; set; }
        public string RAP_CDEC { get; set; }
        public string RAP_DECC { get; set; }
        public long RAP_VPA { get; set; }
        public string RAP_TRAP { get; set; }
        public Nullable<System.DateTime> RAP_FREG { get; set; }
        public string RAP_EST { get; set; }
        public string RAP_TDOC { get; set; }
        public Nullable<System.DateTime> RAP_FRAD { get; set; }
        public System.DateTime RAP_FNOV { get; set; }
        public string RAP_USBD { get; set; }
        public string RAP_USAP { get; set; }
    }
    
}
