//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class REL_INT_MORA
    {
        public string RLIM_NUM { get; set; }
        public string RLIM_DOAD { get; set; }
        public Nullable<decimal> RLIM_VALOR { get; set; }
        public string RLIM_TDOC { get; set; }
        public string RLIM_PER { get; set; }
        public string RLIM_ANO { get; set; }
        public string RLIM_NIT { get; set; }
        public string RLIM_DCOD { get; set; }
        public string RLIM_CDEC { get; set; }
        public string RLIM_USAP { get; set; }
        public string RLIM_USBD { get; set; }
        public System.DateTime RLIM_FREG { get; set; }
    }
    
}
