//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class SECCIONES
    {
        public SECCIONES()
        {
            this.CODE_CDEC = new HashSet<CODE_CDEC>();
            this.CONC_CDEC = new HashSet<CONC_CDEC>();
        }
    
        public string SECC_CODI { get; set; }
        public string SECC_NOMB { get; set; }
        public string SECC_USAP { get; set; }
        public string SECC_USBD { get; set; }
        public Nullable<System.DateTime> SECC_FREG { get; set; }
        public Nullable<System.DateTime> SECC_FNOV { get; set; }
    
        public virtual ICollection<CODE_CDEC> CODE_CDEC { get; set; }
        public virtual ICollection<CONC_CDEC> CONC_CDEC { get; set; }
    }
    
}
