//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class TARIFAS_IMP
    {
        public System.DateTime TARI_FEIN { get; set; }
        public System.DateTime TARI_FEFI { get; set; }
        public string TARI_FORM { get; set; }
        public string TARI_NORM { get; set; }
        public string TARI_IMP { get; set; }
        public string TARI_CODI { get; set; }
        public string TARI_USAP { get; set; }
        public string TARI_USBD { get; set; }
        public Nullable<System.DateTime> TARI_FREG { get; set; }
        public Nullable<System.DateTime> TARI_FNOV { get; set; }
    }
    
}
