//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class TDOC_IDE
    {
        public TDOC_IDE()
        {
            this.TERCEROS = new HashSet<TERCEROS>();
        }
    
        public string TDOC_COD { get; set; }
        public string TDOC_NOM { get; set; }
        public string TDOC_USAP { get; set; }
        public string TDOC_USBD { get; set; }
        public Nullable<System.DateTime> TDOC_FREG { get; set; }
        public Nullable<System.DateTime> TDOC_FNOV { get; set; }
    
        public virtual ICollection<TERCEROS> TERCEROS { get; set; }
    }
    
}
