//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class TIPO_MOV
    {
        public TIPO_MOV()
        {
            this.MOVIMIENTO = new HashSet<MOVIMIENTO>();
        }
    
        public string TMOV_COD { get; set; }
        public string TMOV_NOM { get; set; }
        public string TMOV_USAP { get; set; }
        public string TMOV_USBD { get; set; }
        public Nullable<System.DateTime> TMOV_FREG { get; set; }
        public Nullable<System.DateTime> TMOV_FNOV { get; set; }
    
        public virtual ICollection<MOVIMIENTO> MOVIMIENTO { get; set; }
    }
    
}
