//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class TIPO_CUENTA
    {
        public TIPO_CUENTA()
        {
            this.CTA_BANCO = new HashSet<CTA_BANCO>();
        }
    
        public string TCTA_CODI { get; set; }
        public string TCTA_NOMB { get; set; }
        public string TCTA_USAP { get; set; }
        public string TCTA_USBD { get; set; }
        public Nullable<System.DateTime> TCTA_FREG { get; set; }
        public Nullable<System.DateTime> TCTA_FNOV { get; set; }
    
        public virtual ICollection<CTA_BANCO> CTA_BANCO { get; set; }
    }
    
}
