//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class TIPO_DEC
    {
        public string TDEC_COD { get; set; }
        public string TDEC_NOM { get; set; }
        public Nullable<System.DateTime> TDEC_FIN { get; set; }
        public Nullable<System.DateTime> TDEC_FFI { get; set; }
        public string TDEC_USBD { get; set; }
        public string TDEC_USAP { get; set; }
        public System.DateTime TDEC_FREG { get; set; }
        public System.DateTime TDEC_FNOV { get; set; }
        public string TDEC_CDEC { get; set; }
        public string TDEC_CODI { get; set; }
    
        public virtual CLASE_DEC CLASE_DEC { get; set; }
    }
    
}
