//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class TIPO_DOC_CONS
    {
        public string TIDO_CODI { get; set; }
        public string TIDO_CDEC { get; set; }
        public string TIDO_CONS { get; set; }
        public string TIDO_USAP { get; set; }
        public string TIDO_USBD { get; set; }
        public Nullable<System.DateTime> TIDO_FREG { get; set; }
        public Nullable<System.DateTime> TIDO_FNOV { get; set; }
    
        public virtual TIPO_DOC TIPO_DOC { get; set; }
    }
    
}
