//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class TRAM_TER
    {
        public string TRTE_NIT { get; set; }
        public string TRTE_TRAM { get; set; }
        public string TRTE_USAP { get; set; }
        public string TRTE_USBD { get; set; }
        public Nullable<System.DateTime> TRTE_FREG { get; set; }
        public Nullable<System.DateTime> TRTE_FNOV { get; set; }
    }
    
}
