//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class VH_BG_AUTO_2007
    {
        public int GRUPO { get; set; }
        public string MARCA { get; set; }
        public string LINEA { get; set; }
        public Nullable<int> CILINDRADA { get; set; }
        public Nullable<decimal> V1983 { get; set; }
        public Nullable<decimal> V1984 { get; set; }
        public Nullable<decimal> V1985 { get; set; }
        public Nullable<decimal> V1986 { get; set; }
        public Nullable<decimal> V1987 { get; set; }
        public Nullable<decimal> V1988 { get; set; }
        public Nullable<decimal> V1989 { get; set; }
        public Nullable<decimal> V1990 { get; set; }
        public Nullable<decimal> V1991 { get; set; }
        public Nullable<decimal> V1992 { get; set; }
        public Nullable<decimal> V1993 { get; set; }
        public Nullable<decimal> V1994 { get; set; }
        public Nullable<decimal> V1995 { get; set; }
        public Nullable<decimal> V1996 { get; set; }
        public Nullable<decimal> V1997 { get; set; }
        public Nullable<decimal> V1998 { get; set; }
        public Nullable<decimal> V1999 { get; set; }
        public Nullable<decimal> V2000 { get; set; }
        public Nullable<decimal> V2001 { get; set; }
        public Nullable<decimal> V2002 { get; set; }
        public Nullable<decimal> V2003 { get; set; }
        public Nullable<decimal> V2004 { get; set; }
        public Nullable<decimal> V2005 { get; set; }
        public Nullable<decimal> V2006 { get; set; }
        public string LINEA_H { get; set; }
    }
    
}
