//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class VH_CLASE_CATEGORIA
    {
        public string VCC_CLASE { get; set; }
        public string VCC_CATEGORIA { get; set; }
        public string VCC_VIGENCIA { get; set; }
    }
    
}
