//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class VH_INSTITUTO_TRANSITO
    {
        public string VINS_CODIGO { get; set; }
        public string VINS_DESCRIPCION { get; set; }
    }
    
}
