//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class VH_LIQ_GRUPAL
    {
        public int NRO_LIQG { get; set; }
        public Nullable<System.DateTime> FECHA_INI { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public string USBD { get; set; }
        public string USAP { get; set; }
        public string ESTADO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    }
    
}
