//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class VH_LIQUIDLOG
    {
        public int NRO_LIQG { get; set; }
        public string PLACA { get; set; }
        public string OBSERVACION { get; set; }
        public string LIQUIDO { get; set; }
        public string CATEGORIA_LIQ { get; set; }
        public Nullable<System.DateTime> FECHA_REG { get; set; }
        public string USBD { get; set; }
        public string USAP { get; set; }
        public string VIGENCIALIQ { get; set; }
        public string FILTROVEH { get; set; }
        public string DEC_COD { get; set; }
        public Nullable<int> LIQ_CONS { get; set; }
    }
    
}
